'''
Created on Apr 20, 2017

@author: quannguyen
'''

class LAYER_MAPPING:

	PRBOUNDARY = "prBoundary boundary"
	M1_PIN = "M1 pin"
	M1_TXT = "M1 text"
	M2_PIN = "M2 pin"
	M2_TXT = "M2 text"
	M3_PIN = "M3 pin"
	M3_TXT = "M3 text"
	M4_PIN = "M4 pin"
	M4_TXT = "M4 text"
	M5_PIN = "M5 pin"
	M5_TXT = "M5 text"
	M6_PIN = "M6 pin"
	M6_TXT = "M6 text"
	M7_PIN = "M7 pin"
	M7_TXT = "M7 text"
	M8_PIN = "M8 pin"
	M8_TXT = "M8 text"
	M9_PIN = "M9 pin"
	M9_TXT = "M9 text"
	M10_PIN = "M10 pin"
	M10_TXT = "M10 text"


class LEF_KEYS:

	LEF_CAPACITANCE_KEY = "CAPACITANCE"
	LEF_CLASS_KEY = "CLASS"
	LEF_CUT_KEY = "CUT"
	LEF_DIRECTION_KEY = "DIRECTION"
	LEF_EDGECAPACITANCE_KEY = "EDGECAPACITANCE"
	LEF_END_KEY = "END"
	LEF_FOREIGN_KEY = "FOREIGN"
	LEF_HEIGHT_KEY = "HEIGHT"
	LEF_LAYER_KEY = "LAYER"
	LEF_MACRO_KEY = "MACRO"
	LEF_OBS_KEY = "OBS"
	LEF_OFFSET_KEY = "OFFSET"
	LEF_ORIGIN_KEY = "ORIGIN"
	LEF_PIN_KEY = "PIN"
	LEF_PITCH_KEY = "PITCH"
	LEF_POLYGON_KEY = "POLYGON"
	LEF_PORT_KEY = "PORT"
	LEF_PROPERTY_KEY = "PROPERTY"
	LEF_RECT_KEY = "RECT"
	LEF_RESISTANCE_KEY = "RESISTANCE"
	LEF_ROUTING_KEY = "ROUTING"
	LEF_SHAPE_KEY = "SHAPE"
	LEF_SITE_KEY = "SITE"
	LEF_SIZE_KEY = "SIZE"
	LEF_SPACING_KEY = "SPACING"
	LEF_SPACINGTABLE_KEY = "SPACINGTABLE"
	LEF_SYMMETRY_KEY = "SYMMETRY"
	LEF_THICKNESS_KEY = "THICKNESS"
	LEF_TYPE_KEY = "TYPE"
	LEF_USE_KEY = "USE"
	LEF_VIA_KEY = "VIA"
	LEF_WIDTH_KEY = "WIDTH"
	
	LIST_METAL_KEY="list_metal"
	DICT_GRID_KEY="dict_gird"


class VERILOG_KEYS():
	BRACKET_START_KEY = "("
	BRACKET_END_KEY = ")"

	VERILOG_PARAMETER_KEY = "parameter"
	VERILOG_ALWAYS_KEY = "always"
	VERILOG_BEGIN_KEY = "begin"
	VERILOG_END_KEY = "end"

	VERILOG_END_STATEMENT_KEY = ";"

	VERILOG_PIN_ASSIGNMENT1_KEY = "<="
	VERILOG_PIN_ASSIGNMENT2_KEY = "="
	VERILOG_PIN_ASSIGNMENT3_KEY = "assign"

	VERILOG_PIN_REG_KEY = "reg"

	VERILOG_START_MODULE_KEY = "module"
	VERILOG_START_PRIMITIVE_KEY = "primitive"
	VERILOG_END_MODULE_KEY = "endmodule"
	VERILOG_END_PRIMITIVE_KEY = "endprimitive"
	VERILOG_PIN_INPUT_KEY = "input"
	VERILOG_PIN_OUTPUT_KEY = "output"
	VERILOG_PIN_INOUT_KEY = "inout"
	VERILOG_PIN_START_BUS_KEY = "["
	VERILOG_PIN_END_BUS_KEY = "]"
	VERILOG_START_IF_KEY = "`ifdef"
	VERILOG_END_IF_KEY = "`endif"
	VERILOG_CONDITION_KEY = "CONDITION"

	VERILOG_SPECIFY_KEY = "specify"
	VERILOG_END_SPECIFY_KEY = "endspecify"
	VERILOG_OP_AND_KEY = "and"
	VERILOG_OP_NAND_KEY = "nand"
	VERILOG_OP_OR_KEY = "or"
	VERILOG_OP_NOR_KEY = "nor"
	VERILOG_OP_XOR_KEY = "xor"
	VERILOG_OP_XNOR_KEY = "xnor"
	VERILOG_OP_NOT_KEY = "not"
	VERILOG_OP_BUF_KEY = "buf"
	VERILOG_OP_BUFIF0_KEY = "bufif0"
	VERILOG_OP_BUFIF1_KEY = "bufif1"
	VERILOG_OP_NOTIF0_KEY = "notif0"
	VERILOG_OP_NOTIF1_KEY = "notif1"

	VERILOG_TIMESCALE = "`timescale"
	
	VERILOG_SPECIFY_RELATED_PIN = "related_pin"
	VERILOG_SPECIFY_TIMING_TYPE = "timing_type"
	VERILOG_SPECIFY_TIMING_SENSE = "timing_sense"
	VERILOG_SPECIFY_HOLD = "$hold"
	VERILOG_SPECIFY_SETUPHOLD = "$setuphold"
	VERILOG_SPECIFY_SETUP = "$setup"
	VERILOG_SPECIFY_RECOVERY = "recovery"
	VERILOG_SPECIFY_REMOVAL = "removal"
	VERILOG_SPECIFY_WIDTH = "width"
	VERILOG_SPECIFY_DATA = "data"
	VERILOG_SPECIFY_NEGEDGE = "negedge"
	VERILOG_SPECIFY_POSEDGE = "posedge"
	VERILOG_SPECIFY_PERIOD = "period"
	
	VERILOG_SPECIFY_RELATED_PIN_THREE_STATE = ["OE",]
	VERILOG_SPECIFY_RELATED_PIN_CLOCKED = ["CP",]
	VERILOG_SPECIFY_RELATED_PIN_UNCOMBINATIONAL = ["CDN", "SDN"]
	
	VERILOG_SPECIFY_TIMING_SENSE_POSITIVE_UNATE = "positive_unate"
	VERILOG_SPECIFY_TIMING_SENSE_NEGATIVE_UNATE = "negative_unate"
	
	VERILOG_SPECIFY_TIMING_TYPE_COMBINATIONAL = "combinational"
	VERILOG_SPECIFY_TIMING_TYPE_COMBINATIONAL_RISE = "combinational_rise"
	VERILOG_SPECIFY_TIMING_TYPE_COMBINATIONAL_FALL = "combinational_fall"
	VERILOG_SPECIFY_TIMING_TYPE_THREE_STATE_DISABLE = "three_state_disable"
	VERILOG_SPECIFY_TIMING_TYPE_THREE_STATE_ENABLE = "three_state_enable"
	VERILOG_SPECIFY_TIMING_TYPE_PRESET = "preset"
	VERILOG_SPECIFY_TIMING_TYPE_CLEAR = "clear"
	VERILOG_SPECIFY_TIMING_TYPE_HOLD_FALLING = "hold_falling"
	VERILOG_SPECIFY_TIMING_TYPE_HOLD_RISING = "hold_rising"
	VERILOG_SPECIFY_TIMING_TYPE_SETUPHOLD_FALLING = "setuphold_falling"
	VERILOG_SPECIFY_TIMING_TYPE_SETUPHOLD_RISING = "setuphold_rising"
	VERILOG_SPECIFY_TIMING_TYPE_NON_SEQ_HOLD_RISING = "non_seq_hold_rising"
	VERILOG_SPECIFY_TIMING_TYPE_NON_SEQ_HOLD_FALLING = "non_seq_hold_falling"
	VERILOG_SPECIFY_TIMING_TYPE_NON_SEQ_SETUPHOLD_RISING = "non_seq_sethold_rising"
	VERILOG_SPECIFY_TIMING_TYPE_NON_SEQ_SETUPHOLD_FALLING = "non_seq_sethold_falling"
	VERILOG_SPECIFY_TIMING_TYPE_SETUP_FALLING = "setup_falling"
	VERILOG_SPECIFY_TIMING_TYPE_SETUP_RISING = "setup_rising"
	VERILOG_SPECIFY_TIMING_TYPE_NON_SEQ_SETUP_RISING = "non_seq_setup_rising"
	VERILOG_SPECIFY_TIMING_TYPE_NON_SEQ_SETUP_FALLING = "non_seq_setup_falling"
	VERILOG_SPECIFY_TIMING_TYPE_FALLING_EDGE = "falling_edge"
	VERILOG_SPECIFY_TIMING_TYPE_RISING_EDGE = "rising_edge"
	
	VERILOG_SPECIFY_TIMING_TYPE_RECOVERY_FALLING = "recovery_falling"
	VERILOG_SPECIFY_TIMING_TYPE_RECOVERY_RISING = "recovery_rising"
	
	VERILOG_SPECIFY_TIMING_TYPE_REMOVAL_FALLING = "removal_falling"
	VERILOG_SPECIFY_TIMING_TYPE_REMOVAL_RISING = "removal_rising"
	
	VERILOG_SPECIFY_TIMING_TYPE_MIN_PULSE_WIDTH = "min_pulse_width"
	VERILOG_SPECIFY_TIMING_TYPE_MAX_PULSE_WIDTH = "max_pulse_width"
	VERILOG_SPECIFY_TIMING_TYPE_MINIMUM_PERIOD = "minimum_period"

class LIB_KEYS():
	BRACKET_START_KEY = "{"
	BRACKET_END_KEY = "}"

	CONTINUE_KEY = "\\"
	LIBRARY_KEY = "library"
	CELL_KEY = "cell"
	PIN_KEY = "pin"

	LIB_PIN_START_BUS_KEY = "["
	LIB_PIN_END_BUS_KEY = "]"

	PIN_BUS_KEY = "bus"
	PIN_PG_KEY = "pg_pin"

	LEAKAGE_POWER_KEY = "leakage_power"
	PG_PIN_KEY = "pg_pin"

	LEAKAGE_POWER_KEY_RELATED_PG_PIN = "related_pg_pin"
	LEAKAGE_POWER_KEY_WHEN = "when"
	LEAKAGE_POWER_KEY_VALUE = "value"

	PG_PIN_KEY_VOLTAGE_NAME = "voltage_name"
	PG_PIN_KEY_PG_TYPE = "pg_type"

	PIN_INTERNAL_POWER_KEY = "internal_power"
	PIN_TIMING_KEY = "timing"

	LIBRARY_SIMPLE_BUS_NAMING_STYLE_KEY = "bus_naming_style"
	LIBRARY_SIMPLE_COMMENT_KEY = "comment"
	LIBRARY_SIMPLE_CURRENT_UNIT_KEY = "current_unit"
	LIBRARY_SIMPLE_DELAY_MODEL_KEY = "delay_model"
	LIBRARY_SIMPLE_EM_TEMP_DEGRADATION_FACTOR_KEY = "em_temp_degradation_factor"
	LIBRARY_SIMPLE_FPGA_TECHNOLOGY_KEY = "fpga_technology"
	LIBRARY_SIMPLE_IN_PLACE_SWAP_MODE_KEY = "in_place_swap_mode"
	LIBRARY_SIMPLE_INPUT_THRESHOLD_PCT_FALL_KEY = "input_threshold_pct_fall"
	LIBRARY_SIMPLE_INPUT_THRESHOLD_PCT_RISE_KEY = "input_threshold_pct_rise"
	LIBRARY_SIMPLE_LEAKAGE_POWER_UNIT_KEY = "leakage_power_unit"
	LIBRARY_SIMPLE_NOM_CALC_MODE_KEY = "nom_calc_mode"
	LIBRARY_SIMPLE_NOM_PROCESS_KEY = "nom_process"
	LIBRARY_SIMPLE_NOM_TEMPERATURE_KEY = "nom_temperature"
	LIBRARY_SIMPLE_NOM_VOLTAGE_KEY = "nom_voltage"
	LIBRARY_SIMPLE_OUTPUT_THRESHOLD_PCT_FALL_KEY = "output_threshold_pct_fall"
	LIBRARY_SIMPLE_OUTPUT_THRESHOLD_PCT_RISE_KEY = "output_threshold_pct_rise"
	LIBRARY_SIMPLE_PIECE_TYPE_KEY = "piece_type"
	LIBRARY_SIMPLE_POWER_MODEL_KEY = "power_model"
	LIBRARY_SIMPLE_PREFERRED_OUTPUT_PAD_SLEW_RATE_CONTROL_KEY = "preferred_output_pad_slew_rate_control"
	LIBRARY_SIMPLE_PREFERRED_INPUT_PAD_VOLTAGE_KEY = "preferred_input_pad_voltage"
	LIBRARY_SIMPLE_PREFERRED_OUTPUT_PAD_VOLTAGE_KEY = "preferred_output_pad_voltage"
	LIBRARY_SIMPLE_PULLING_RESISTANCE_UNIT_KEY = "pulling_resistance_unit"
	LIBRARY_SIMPLE_REVISION_KEY = "revision"
	LIBRARY_SIMPLE_SIMULATION_KEY = "simulation"
	LIBRARY_SIMPLE_SLEW_DERATE_FROM_LIBRARY_KEY = "slew_derate_from_library"
	LIBRARY_SIMPLE_SLEW_LOWER_THRESHOLD_PCT_FALL_KEY = "slew_lower_threshold_pct_fall"
	LIBRARY_SIMPLE_SLEW_LOWER_THRESHOLD_PCT_RISE_KEY = "slew_lower_threshold_pct_rise"
	LIBRARY_SIMPLE_SLEW_UPPER_THRESHOLD_PCT_FALL_KEY = "slew_upper_threshold_pct_fall"
	LIBRARY_SIMPLE_SLEW_UPPER_THRESHOLD_PCT_RISE_KEY = "slew_upper_threshold_pct_rise"
	LIBRARY_SIMPLE_TIME_UNIT_KEY = "time_unit"
	LIBRARY_SIMPLE_VOLTAGE_UNIT_KEY = "voltage_unit"
	LIBRARY_SIMPLE_DEFAULT_CELL_LEAKAGE_POWER_KEY = "default_cell_leakage_power"
	LIBRARY_SIMPLE_DEFAULT_CONNECTION_CLASS_KEY = "default_connection_class"
	LIBRARY_SIMPLE_DEFAULT_FALL_DELAY_INTERCEPT_KEY = "default_fall_delay_intercept"
	LIBRARY_SIMPLE_DEFAULT_FALL_PIN_RESISTANCE_KEY = "default_fall_pin_resistance"
	LIBRARY_SIMPLE_DEFAULT_FANOUT_LOAD_KEY = "default_fanout_load"
	LIBRARY_SIMPLE_DEFAULT_INOUT_PIN_CAP_KEY = "default_inout_pin_cap"
	LIBRARY_SIMPLE_DEFAULT_INOUT_PIN_FALL_RES_KEY = "default_inout_pin_fall_res"
	LIBRARY_SIMPLE_DEFAULT_INOUT_PIN_RISE_RES_KEY = "default_inout_pin_rise_res"
	LIBRARY_SIMPLE_DEFAULT_INPUT_PIN_CAP_KEY = "default_input_pin_cap"
	LIBRARY_SIMPLE_DEFAULT_INTRINSIC_FALL_KEY = "default_intrinsic_fall"
	LIBRARY_SIMPLE_DEFAULT_INTRINSIC_RISE_KEY = "default_intrinsic_rise"
	LIBRARY_SIMPLE_DEFAULT_LEAKAGE_POWER_DENSITY_KEY = "default_leakage_power_density"
	LIBRARY_SIMPLE_DEFAULT_MAX_CAPACITANCE_KEY = "default_max_capacitance"
	LIBRARY_SIMPLE_DEFAULT_MAX_FANOUT_KEY = "default_max_fanout"
	LIBRARY_SIMPLE_DEFAULT_MAX_TRANSITION_KEY = "default_max_transition"
	LIBRARY_SIMPLE_DEFAULT_MAX_UTILIZATION_KEY = "default_max_utilization"
	LIBRARY_SIMPLE_DEFAULT_MIN_POROSITY_KEY = "default_min_porosity"
	LIBRARY_SIMPLE_DEFAULT_OPERATING_CONDITIONS_KEY = "default_operating_conditions"
	LIBRARY_SIMPLE_DEFAULT_OUTPUT_PIN_CAP_KEY = "default_output_pin_cap"
	LIBRARY_SIMPLE_DEFAULT_OUTPUT_PIN_FALL_RES_KEY = "default_output_pin_fall_res"
	LIBRARY_SIMPLE_DEFAULT_OUTPUT_PIN_RISE_RES_KEY = "default_output_pin_rise_res"
	LIBRARY_SIMPLE_DEFAULT_RISE_DELAY_INTERCEPT_KEY = "default_rise_delay_intercept"
	LIBRARY_SIMPLE_DEFAULT_RISE_PIN_RESISTANCE_KEY = "default_rise_pin_resistance"
	LIBRARY_SIMPLE_DEFAULT_SLOPE_FALL_KEY = "default_slope_fall"
	LIBRARY_SIMPLE_DEFAULT_SLOPE_RISE_KEY = "default_slope_rise"
	LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_KEY = "default_wire_load"
	LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_AREA_KEY = "default_wire_load_area"
	LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_CAPACITANCE_KEY = "default_wire_load_capacitance"
	LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_MODE_KEY = "default_wire_load_mode"
	LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_RESISTANCE_KEY = "default_wire_load_resistance"
	LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_SELECTION_KEY = "default_wire_load_selection"
	LIBRARY_SIMPLE_K_PROCESS_CELL_FALL_KEY = "k_process_cell_fall"
	LIBRARY_SIMPLE_K_PROCESS_CELL_LEAKAGE_POWER_KEY = "k_process_cell_leakage_power"
	LIBRARY_SIMPLE_K_PROCESS_CELL_RISE_KEY = "k_process_cell_rise"
	LIBRARY_SIMPLE_K_PROCESS_DRIVE_CURRENT_KEY = "k_process_drive_current"
	LIBRARY_SIMPLE_K_PROCESS_DRIVE_FALL_KEY = "k_process_drive_fall"
	LIBRARY_SIMPLE_K_PROCESS_DRIVE_RISE_KEY = "k_process_drive_rise"
	LIBRARY_SIMPLE_K_PROCESS_FALL_PIN_RESISTANCE_KEY = "k_process_fall_pin_resistance"
	LIBRARY_SIMPLE_K_PROCESS_FALL_PROPAGATION_KEY = "k_process_fall_propagation"
	LIBRARY_SIMPLE_K_PROCESS_FALL_TRANSITION_KEY = "k_process_fall_transition"
	LIBRARY_SIMPLE_K_PROCESS_HOLD_FALL_KEY = "k_process_hold_fall"
	LIBRARY_SIMPLE_K_PROCESS_HOLD_RISE_KEY = "k_process_hold_rise"
	LIBRARY_SIMPLE_K_PROCESS_INTERNAL_POWER_KEY = "k_process_internal_power"
	LIBRARY_SIMPLE_K_PROCESS_INTRINSIC_FALL_KEY = "k_process_intrinsic_fall"
	LIBRARY_SIMPLE_K_PROCESS_INTRINSIC_RISE_KEY = "k_process_intrinsic_rise"
	LIBRARY_SIMPLE_K_PROCESS_MIN_PERIOD_KEY = "k_process_min_period"
	LIBRARY_SIMPLE_K_PROCESS_MIN_PULSE_WIDTH_HIGH_KEY = "k_process_min_pulse_width_high"
	LIBRARY_SIMPLE_K_PROCESS_MIN_PULSE_WIDTH_LOW_KEY = "k_process_min_pulse_width_low"
	LIBRARY_SIMPLE_K_PROCESS_NOCHANGE_FALL_KEY = "k_process_nochange_fall"
	LIBRARY_SIMPLE_K_PROCESS_NOCHANGE_RISE_KEY = "k_process_nochange_rise"
	LIBRARY_SIMPLE_K_PROCESS_PIN_CAP_KEY = "k_process_pin_cap"
	LIBRARY_SIMPLE_K_PROCESS_RECOVERY_FALL_KEY = "k_process_recovery_fall"
	LIBRARY_SIMPLE_K_PROCESS_RECOVERY_RISE_KEY = "k_process_recovery_rise"
	LIBRARY_SIMPLE_K_PROCESS_REMOVAL_FALL_KEY = "k_process_removal_fall"
	LIBRARY_SIMPLE_K_PROCESS_REMOVAL_RISE_KEY = "k_process_removal_rise"
	LIBRARY_SIMPLE_K_PROCESS_RISE_DELAY_INTERCEPT_KEY = "k_process_rise_delay_intercept"
	LIBRARY_SIMPLE_K_PROCESS_RISE_PIN_RESISTANCE_KEY = "k_process_rise_pin_resistance"
	LIBRARY_SIMPLE_K_PROCESS_RISE_PROPAGATION_KEY = "k_process_rise_propagation"
	LIBRARY_SIMPLE_K_PROCESS_RISE_TRANSITION_KEY = "k_process_rise_transition"
	LIBRARY_SIMPLE_K_PROCESS_SETUP_FALL_KEY = "k_process_setup_fall"
	LIBRARY_SIMPLE_K_PROCESS_SETUP_RISE_KEY = "k_process_setup_rise"
	LIBRARY_SIMPLE_K_PROCESS_SKEW_FALL_KEY = "k_process_skew_fall"
	LIBRARY_SIMPLE_K_PROCESS_SKEW_RISE_KEY = "k_process_skew_rise"
	LIBRARY_SIMPLE_K_PROCESS_SLOPE_FALL_KEY = "k_process_slope_fall"
	LIBRARY_SIMPLE_K_PROCESS_SLOPE_RISE_KEY = "k_process_slope_rise"
	LIBRARY_SIMPLE_K_PROCESS_WIRE_CAP_KEY = "k_process_wire_cap"
	LIBRARY_SIMPLE_K_PROCESS_WIRE_RES_KEY = "k_process_wire_res"
	LIBRARY_SIMPLE_K_TEMP_CELL_RISE_KEY = "k_temp_cell_rise"
	LIBRARY_SIMPLE_K_TEMP_CELL_FALL_KEY = "k_temp_cell_fall"
	LIBRARY_SIMPLE_K_TEMP_CELL_LEAKAGE_POWER_KEY = "k_temp_cell_leakage_power"
	LIBRARY_SIMPLE_K_TEMP_DRIVE_CURRENT_KEY = "k_temp_drive_current"
	LIBRARY_SIMPLE_K_TEMP_DRIVE_FALL_KEY = "k_temp_drive_fall"
	LIBRARY_SIMPLE_K_TEMP_DRIVE_RISE_KEY = "k_temp_drive_rise"
	LIBRARY_SIMPLE_K_TEMP_FALL_DELAY_INTERCEPT_KEY = "k_temp_fall_delay_intercept"
	LIBRARY_SIMPLE_K_TEMP_FALL_PIN_RESISTANCE_KEY = "k_temp_fall_pin_resistance"
	LIBRARY_SIMPLE_K_TEMP_FALL_PROPAGATION_KEY = "k_temp_fall_propagation"
	LIBRARY_SIMPLE_K_TEMP_FALL_TRANSITION_KEY = "k_temp_fall_transition"
	LIBRARY_SIMPLE_K_TEMP_HOLD_FALL_KEY = "k_temp_hold_fall"
	LIBRARY_SIMPLE_K_TEMP_HOLD_RISE_KEY = "k_temp_hold_rise"
	LIBRARY_SIMPLE_K_TEMP_INTERNAL_POWER_KEY = "k_temp_internal_power"
	LIBRARY_SIMPLE_K_TEMP_INTRINSIC_FALL_KEY = "k_temp_intrinsic_fall"
	LIBRARY_SIMPLE_K_TEMP_INTRINSIC_RISE_KEY = "k_temp_intrinsic_rise"
	LIBRARY_SIMPLE_K_TEMP_MIN_PERIOD_KEY = "k_temp_min_period"
	LIBRARY_SIMPLE_K_TEMP_MIN_PULSE_WIDTH_HIGH_KEY = "k_temp_min_pulse_width_high"
	LIBRARY_SIMPLE_K_TEMP_MIN_PULSE_WIDTH_LOW_KEY = "k_temp_min_pulse_width_low"
	LIBRARY_SIMPLE_K_TEMP_NOCHANGE_FALL_KEY = "k_temp_nochange_fall"
	LIBRARY_SIMPLE_K_TEMP_NOCHANGE_RISE_KEY = "k_temp_nochange_rise"
	LIBRARY_SIMPLE_K_TEMP_PIN_CAP_KEY = "k_temp_pin_cap"
	LIBRARY_SIMPLE_K_TEMP_RECOVERY_FALL_KEY = "k_temp_recovery_fall"
	LIBRARY_SIMPLE_K_TEMP_RECOVERY_RISE_KEY = "k_temp_recovery_rise"
	LIBRARY_SIMPLE_K_TEMP_REMOVAL_FALL_KEY = "k_temp_removal_fall"
	LIBRARY_SIMPLE_K_TEMP_REMOVAL_RISE_KEY = "k_temp_removal_rise"
	LIBRARY_SIMPLE_K_TEMP_RISE_DELAY_INTERCEPT_KEY = "k_temp_rise_delay_intercept"
	LIBRARY_SIMPLE_K_TEMP_RISE_PIN_RESISTANCE_KEY = "k_temp_rise_pin_resistance"
	LIBRARY_SIMPLE_K_TEMP_RISE_PROPOGATION_KEY = "k_temp_rise_propogation"
	LIBRARY_SIMPLE_K_TEMP_RISE_TRANSITION_KEY = "k_temp_rise_transition"
	LIBRARY_SIMPLE_K_TEMP_RISE_WIRE_RESISTANCE_KEY = "k_temp_rise_wire_resistance"
	LIBRARY_SIMPLE_K_TEMP_SETUP_FALL_KEY = "k_temp_setup_fall"
	LIBRARY_SIMPLE_K_TEMP_SETUP_RISE_KEY = "k_temp_setup_rise"
	LIBRARY_SIMPLE_K_TEMP_SKEW_FALL_KEY = "k_temp_skew_fall"
	LIBRARY_SIMPLE_K_TEMP_SKEW_RISE_KEY = "k_temp_skew_rise"
	LIBRARY_SIMPLE_K_TEMP_SLOPE_FALL_KEY = "k_temp_slope_fall"
	LIBRARY_SIMPLE_K_TEMP_SLOPE_RISE_KEY = "k_temp_slope_rise"
	LIBRARY_SIMPLE_K_TEMP_WIRE_CAP_KEY = "k_temp_wire_cap"
	LIBRARY_SIMPLE_K_TEMP_WIRE_RES_KEY = "k_temp_wire_res"
	LIBRARY_SIMPLE_K_VOLT_CELL_FALL_KEY = "k_volt_cell_fall"
	LIBRARY_SIMPLE_K_VOLT_CELL_LEAKAGE_POWER_KEY = "k_volt_cell_leakage_power"
	LIBRARY_SIMPLE_K_VOLT_CELL_RISE_KEY = "k_volt_cell_rise"
	LIBRARY_SIMPLE_K_VOLT_DRIVE_CURRENT_KEY = "k_volt_drive_current"
	LIBRARY_SIMPLE_K_VOLT_DRIVE_FALL_KEY = "k_volt_drive_fall"
	LIBRARY_SIMPLE_K_VOLT_DRIVE_RISE_KEY = "k_volt_drive_rise"
	LIBRARY_SIMPLE_K_VOLT_FALL_PIN_RESISTANCE_KEY = "k_volt_fall_pin_resistance"
	LIBRARY_SIMPLE_K_VOLT_FALL_PROPAGATION_KEY = "k_volt_fall_propagation"
	LIBRARY_SIMPLE_K_VOLT_FALL_TRANSITION_KEY = "k_volt_fall_transition"
	LIBRARY_SIMPLE_K_VOLT_HOLD_FALL_KEY = "k_volt_hold_fall"
	LIBRARY_SIMPLE_K_VOLT_HOLD_RISE_KEY = "k_volt_hold_rise"
	LIBRARY_SIMPLE_K_VOLT_INTERNAL_POWER_KEY = "k_volt_internal_power"
	LIBRARY_SIMPLE_K_VOLT_INTRINSIC_FALL_KEY = "k_volt_intrinsic_fall"
	LIBRARY_SIMPLE_K_VOLT_INTRINSIC_RISE_KEY = "k_volt_intrinsic_rise"
	LIBRARY_SIMPLE_K_VOLT_MIN_PERIOD_KEY = "k_volt_min_period"
	LIBRARY_SIMPLE_K_VOLT_MIN_PULSE_WIDTH_HIGH_KEY = "k_volt_min_pulse_width_high"
	LIBRARY_SIMPLE_K_VOLT_MIN_PULSE_WIDTH_LOW_KEY = "k_volt_min_pulse_width_low"
	LIBRARY_SIMPLE_K_VOLT_NOCHANGE_FALL_KEY = "k_volt_nochange_fall"
	LIBRARY_SIMPLE_K_VOLT_NOCHANGE_RISE_KEY = "k_volt_nochange_rise"
	LIBRARY_SIMPLE_K_VOLT_PIN_CAP_KEY = "k_volt_pin_cap"
	LIBRARY_SIMPLE_K_VOLT_RECOVERY_FALL_KEY = "k_volt_recovery_fall"
	LIBRARY_SIMPLE_K_VOLT_RECOVERY_RISE_KEY = "k_volt_recovery_rise"
	LIBRARY_SIMPLE_K_VOLT_REMOVAL_FALL_KEY = "k_volt_removal_fall"
	LIBRARY_SIMPLE_K_VOLT_REMOVAL_RISE_KEY = "k_volt_removal_rise"
	LIBRARY_SIMPLE_K_VOLT_RISE_DELAY_INTERCEPT_KEY = "k_volt_rise_delay_intercept"
	LIBRARY_SIMPLE_K_VOLT_RISE_PIN_RESISTANCE_KEY = "k_volt_rise_pin_resistance"
	LIBRARY_SIMPLE_K_VOLT_RISE_PROPAGATION_KEY = "k_volt_rise_propagation"
	LIBRARY_SIMPLE_K_VOLT_RISE_TRANSITION_KEY = "k_volt_rise_transition"
	LIBRARY_SIMPLE_K_VOLT_SETUP_FALL_KEY = "k_volt_setup_fall"
	LIBRARY_SIMPLE_K_VOLT_SETUP_RISE_KEY = "k_volt_setup_rise"
	LIBRARY_SIMPLE_K_VOLT_SKEW_FALL_KEY = "k_volt_skew_fall"
	LIBRARY_SIMPLE_K_VOLT_SKEW_RISE_KEY = "k_volt_skew_rise"
	LIBRARY_SIMPLE_K_VOLT_SLOPE_FALL_KEY = "k_volt_slope_fall"
	LIBRARY_SIMPLE_K_VOLT_SLOPE_RISE_KEY = "k_volt_slope_rise"
	LIBRARY_SIMPLE_K_VOLT_WIRE_CAP_KEY = "k_volt_wire_cap"
	LIBRARY_SIMPLE_K_VOLT_WIRE_RES_KEY = "k_volt_wire_res"


	LIBRARY_COMPLEX_CAPACITIVE_LOAD_UNIT_KEY = "capacitive_load_unit"
	LIBRARY_COMPLEX_DEFAULT_PART_KEY = "default_part"
	LIBRARY_COMPLEX_DEFINE_KEY = "define"
	LIBRARY_COMPLEX_DEFINE_CELL_AREA_KEY = "define_cell_area"
	LIBRARY_COMPLEX_DEFINE_GROUP_KEY = "define_group"
	LIBRARY_COMPLEX_LIBRARY_FEATURES_KEY = "library_features"
	LIBRARY_COMPLEX_PIECE_DEFINE_KEY = "piece_define"
	LIBRARY_COMPLEX_ROUTING_LAYERS_KEY = "routing_layers"
	LIBRARY_COMPLEX_TECHNOLOGY_KEY = "technology"
	LIBRARY_COMPLEX_VOLTAGE_MAP_KEY = "voltage_map"


	LIBRARY_GROUP_BASE_CURVES_KEY = "base_curves"
	LIBRARY_GROUP_BASE_CURVE_TYPE_KEY = "base_curve_type"
	LIBRARY_GROUP_CURVE_X_KEY = "curve_x"
	LIBRARY_GROUP_CURVE_Y_KEY = "curve_y"
	LIBRARY_GROUP_COMPACT_LUT_TEMPLATE_KEY = "compact_lut_template"
	LIBRARY_GROUP_BASE_CURVES_GROUP_KEY = "base_curves_group"
	LIBRARY_GROUP_VARIABLE_1_KEY = "variable_1"
	LIBRARY_GROUP_VARIABLE_2_KEY = "variable_2"
	LIBRARY_GROUP_VARIABLE_3_KEY = "variable_3"
	LIBRARY_GROUP_VARIABLE_4_KEY = "variable_4"
	LIBRARY_GROUP_INDEX_1_KEY = "index_1"
	LIBRARY_GROUP_INDEX_2_KEY = "index_2"
	LIBRARY_GROUP_INDEX_3_KEY = "index_3"
	LIBRARY_GROUP_DC_CURRENT_TEMPLATE_KEY = "dc_current_template"
	LIBRARY_GROUP_EM_LUT_TEMPLATE_KEY = "em_lut_template"
	LIBRARY_GROUP_FALL_NET_DELAY_KEY = "fall_net_delay"
	LIBRARY_GROUP_FALL_TRANSITION_DEGRADATION_KEY = "fall_transition_degradation"
	LIBRARY_GROUP_FAULTS_LUT_TEMPLATE_KEY = "faults_lut_template"
	LIBRARY_GROUP_INPUT_VOLTAGE_KEY = "input_voltage"
	LIBRARY_GROUP_FPGA_ISD_KEY = "fpga_isd"
	LIBRARY_GROUP_IV_LUT_TEMPLATE_KEY = "iv_lut_template"
	LIBRARY_GROUP_LU_TABLE_TEMPLATE_KEY = "lu_table_template"
	LIBRARY_GROUP_MAXCAP_LUT_TEMPLATE_KEY = "maxcap_lut_template"
	LIBRARY_GROUP_MAXTRANS_LUT_TEMPLATE_KEY = "maxtrans_lut_template"
	LIBRARY_GROUP_NOISE_LUT_TEMPLATE_KEY = "noise_lut_template"
	LIBRARY_GROUP_NORMALIZED_DRIVER_WAVEFORM_KEY = "normalized_driver_waveform"
	LIBRARY_GROUP_OPERATING_CONDITIONS_KEY = "operating_conditions"
	LIBRARY_GROUP_OUTPUT_CURRENT_TEMPLATE_KEY = "output_current_template"
	LIBRARY_GROUP_OUTPUT_VOLTAGE_KEY = "output_voltage"
	LIBRARY_GROUP_PART_KEY = "part"
	LIBRARY_GROUP_PG_CURRENT_TEMPLATE_KEY = "pg_current_template"
	LIBRARY_GROUP_POLY_TEMPLATE_KEY = "poly_template"
	LIBRARY_GROUP_POWER_LUT_TEMPLATE_KEY = "power_lut_template"
	LIBRARY_GROUP_POWER_POLY_TEMPLATE_KEY = "power_poly_template"
	LIBRARY_GROUP_POWER_SUPPLY_KEY = "power_supply"
	LIBRARY_GROUP_PROPAGATION_LUT_TEMPLATE_KEY = "propagation_lut_template"
	LIBRARY_GROUP_RISE_NET_DELAY_KEY = "rise_net_delay"
	LIBRARY_GROUP_RISE_TRANSITION_DEGRADATION_KEY = "rise_transition_degradation"
	LIBRARY_GROUP_SCALED_CELL_KEY = "scaled_cell"
	LIBRARY_GROUP_SENSITIZATION_KEY = "sensitization"
	LIBRARY_GROUP_PIN_NAMES_KEY = "pin_names"
	LIBRARY_GROUP_VECTOR_KEY = "vector"
	LIBRARY_GROUP_SCALING_FACTORS_KEY = "scaling_factors"
	LIBRARY_GROUP_TIMING_KEY = "timing"
	LIBRARY_GROUP_TIMING_RANGE_KEY = "timing_range"
	LIBRARY_GROUP_TYPE_KEY = "type"
	LIBRARY_GROUP_USER_PARAMETERS_KEY = "user_parameters"
	LIBRARY_GROUP_WIRE_LOAD_KEY = "wire_load"
	LIBRARY_GROUP_WIRE_LOAD_SELECTION_KEY = "wire_load_selection"
	LIBRARY_GROUP_WIRE_LOAD_TABLE_KEY = "wire_load_table"

	LIBRARY_SIMPLE_ATTR_KEY = [LIBRARY_SIMPLE_BUS_NAMING_STYLE_KEY, LIBRARY_SIMPLE_COMMENT_KEY, LIBRARY_SIMPLE_CURRENT_UNIT_KEY, LIBRARY_SIMPLE_DELAY_MODEL_KEY,
							LIBRARY_SIMPLE_EM_TEMP_DEGRADATION_FACTOR_KEY, LIBRARY_SIMPLE_FPGA_TECHNOLOGY_KEY, LIBRARY_SIMPLE_IN_PLACE_SWAP_MODE_KEY,
							LIBRARY_SIMPLE_INPUT_THRESHOLD_PCT_FALL_KEY, LIBRARY_SIMPLE_INPUT_THRESHOLD_PCT_RISE_KEY, LIBRARY_SIMPLE_LEAKAGE_POWER_UNIT_KEY,
							LIBRARY_SIMPLE_NOM_CALC_MODE_KEY, LIBRARY_SIMPLE_NOM_PROCESS_KEY, LIBRARY_SIMPLE_NOM_TEMPERATURE_KEY, LIBRARY_SIMPLE_NOM_VOLTAGE_KEY,
							LIBRARY_SIMPLE_OUTPUT_THRESHOLD_PCT_FALL_KEY, LIBRARY_SIMPLE_OUTPUT_THRESHOLD_PCT_RISE_KEY, LIBRARY_SIMPLE_PIECE_TYPE_KEY,
							LIBRARY_SIMPLE_POWER_MODEL_KEY, LIBRARY_SIMPLE_PREFERRED_OUTPUT_PAD_SLEW_RATE_CONTROL_KEY, LIBRARY_SIMPLE_PREFERRED_INPUT_PAD_VOLTAGE_KEY,
							LIBRARY_SIMPLE_PREFERRED_OUTPUT_PAD_VOLTAGE_KEY, LIBRARY_SIMPLE_PULLING_RESISTANCE_UNIT_KEY, LIBRARY_SIMPLE_REVISION_KEY, LIBRARY_SIMPLE_SIMULATION_KEY,
							LIBRARY_SIMPLE_SLEW_DERATE_FROM_LIBRARY_KEY, LIBRARY_SIMPLE_SLEW_LOWER_THRESHOLD_PCT_FALL_KEY, LIBRARY_SIMPLE_SLEW_LOWER_THRESHOLD_PCT_RISE_KEY,
							LIBRARY_SIMPLE_SLEW_UPPER_THRESHOLD_PCT_FALL_KEY, LIBRARY_SIMPLE_SLEW_UPPER_THRESHOLD_PCT_RISE_KEY, LIBRARY_SIMPLE_TIME_UNIT_KEY,
							LIBRARY_SIMPLE_VOLTAGE_UNIT_KEY, LIBRARY_SIMPLE_DEFAULT_CELL_LEAKAGE_POWER_KEY, LIBRARY_SIMPLE_DEFAULT_CONNECTION_CLASS_KEY,
							LIBRARY_SIMPLE_DEFAULT_FALL_DELAY_INTERCEPT_KEY, LIBRARY_SIMPLE_DEFAULT_FALL_PIN_RESISTANCE_KEY, LIBRARY_SIMPLE_DEFAULT_FANOUT_LOAD_KEY,
							LIBRARY_SIMPLE_DEFAULT_INOUT_PIN_CAP_KEY, LIBRARY_SIMPLE_DEFAULT_INOUT_PIN_FALL_RES_KEY, LIBRARY_SIMPLE_DEFAULT_INOUT_PIN_RISE_RES_KEY,
							LIBRARY_SIMPLE_DEFAULT_INPUT_PIN_CAP_KEY, LIBRARY_SIMPLE_DEFAULT_INTRINSIC_FALL_KEY, LIBRARY_SIMPLE_DEFAULT_INTRINSIC_RISE_KEY,
							LIBRARY_SIMPLE_DEFAULT_LEAKAGE_POWER_DENSITY_KEY, LIBRARY_SIMPLE_DEFAULT_MAX_CAPACITANCE_KEY, LIBRARY_SIMPLE_DEFAULT_MAX_FANOUT_KEY,
							LIBRARY_SIMPLE_DEFAULT_MAX_TRANSITION_KEY, LIBRARY_SIMPLE_DEFAULT_MAX_UTILIZATION_KEY, LIBRARY_SIMPLE_DEFAULT_MIN_POROSITY_KEY,
							LIBRARY_SIMPLE_DEFAULT_OPERATING_CONDITIONS_KEY, LIBRARY_SIMPLE_DEFAULT_OUTPUT_PIN_CAP_KEY, LIBRARY_SIMPLE_DEFAULT_OUTPUT_PIN_FALL_RES_KEY,
							LIBRARY_SIMPLE_DEFAULT_OUTPUT_PIN_RISE_RES_KEY, LIBRARY_SIMPLE_DEFAULT_RISE_DELAY_INTERCEPT_KEY, LIBRARY_SIMPLE_DEFAULT_RISE_PIN_RESISTANCE_KEY,
							LIBRARY_SIMPLE_DEFAULT_SLOPE_FALL_KEY, LIBRARY_SIMPLE_DEFAULT_SLOPE_RISE_KEY, LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_KEY, LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_AREA_KEY,
							LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_CAPACITANCE_KEY, LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_MODE_KEY, LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_RESISTANCE_KEY,
							LIBRARY_SIMPLE_DEFAULT_WIRE_LOAD_SELECTION_KEY, LIBRARY_SIMPLE_K_PROCESS_CELL_FALL_KEY, LIBRARY_SIMPLE_K_PROCESS_CELL_LEAKAGE_POWER_KEY,
							LIBRARY_SIMPLE_K_PROCESS_CELL_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_DRIVE_CURRENT_KEY, LIBRARY_SIMPLE_K_PROCESS_DRIVE_FALL_KEY,
							LIBRARY_SIMPLE_K_PROCESS_DRIVE_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_FALL_PIN_RESISTANCE_KEY, LIBRARY_SIMPLE_K_PROCESS_FALL_PROPAGATION_KEY,
							LIBRARY_SIMPLE_K_PROCESS_FALL_TRANSITION_KEY, LIBRARY_SIMPLE_K_PROCESS_HOLD_FALL_KEY, LIBRARY_SIMPLE_K_PROCESS_HOLD_RISE_KEY,
							LIBRARY_SIMPLE_K_PROCESS_INTERNAL_POWER_KEY, LIBRARY_SIMPLE_K_PROCESS_INTRINSIC_FALL_KEY, LIBRARY_SIMPLE_K_PROCESS_INTRINSIC_RISE_KEY,
							LIBRARY_SIMPLE_K_PROCESS_MIN_PERIOD_KEY, LIBRARY_SIMPLE_K_PROCESS_MIN_PULSE_WIDTH_HIGH_KEY, LIBRARY_SIMPLE_K_PROCESS_MIN_PULSE_WIDTH_LOW_KEY,
							LIBRARY_SIMPLE_K_PROCESS_NOCHANGE_FALL_KEY, LIBRARY_SIMPLE_K_PROCESS_NOCHANGE_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_PIN_CAP_KEY,
							LIBRARY_SIMPLE_K_PROCESS_RECOVERY_FALL_KEY, LIBRARY_SIMPLE_K_PROCESS_RECOVERY_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_REMOVAL_FALL_KEY,
							LIBRARY_SIMPLE_K_PROCESS_REMOVAL_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_RISE_DELAY_INTERCEPT_KEY, LIBRARY_SIMPLE_K_PROCESS_RISE_PIN_RESISTANCE_KEY,
							LIBRARY_SIMPLE_K_PROCESS_RISE_PROPAGATION_KEY, LIBRARY_SIMPLE_K_PROCESS_RISE_TRANSITION_KEY, LIBRARY_SIMPLE_K_PROCESS_SETUP_FALL_KEY,
							LIBRARY_SIMPLE_K_PROCESS_SETUP_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_SKEW_FALL_KEY, LIBRARY_SIMPLE_K_PROCESS_SKEW_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_SLOPE_FALL_KEY,
							LIBRARY_SIMPLE_K_PROCESS_SLOPE_RISE_KEY, LIBRARY_SIMPLE_K_PROCESS_WIRE_CAP_KEY, LIBRARY_SIMPLE_K_PROCESS_WIRE_RES_KEY, LIBRARY_SIMPLE_K_TEMP_CELL_RISE_KEY,
							LIBRARY_SIMPLE_K_TEMP_CELL_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_CELL_LEAKAGE_POWER_KEY, LIBRARY_SIMPLE_K_TEMP_DRIVE_CURRENT_KEY, LIBRARY_SIMPLE_K_TEMP_DRIVE_FALL_KEY,
							LIBRARY_SIMPLE_K_TEMP_DRIVE_RISE_KEY, LIBRARY_SIMPLE_K_TEMP_FALL_DELAY_INTERCEPT_KEY, LIBRARY_SIMPLE_K_TEMP_FALL_PIN_RESISTANCE_KEY,
							LIBRARY_SIMPLE_K_TEMP_FALL_PROPAGATION_KEY, LIBRARY_SIMPLE_K_TEMP_FALL_TRANSITION_KEY, LIBRARY_SIMPLE_K_TEMP_HOLD_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_HOLD_RISE_KEY,
							LIBRARY_SIMPLE_K_TEMP_INTERNAL_POWER_KEY, LIBRARY_SIMPLE_K_TEMP_INTRINSIC_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_INTRINSIC_RISE_KEY, LIBRARY_SIMPLE_K_TEMP_MIN_PERIOD_KEY,
							LIBRARY_SIMPLE_K_TEMP_MIN_PULSE_WIDTH_HIGH_KEY, LIBRARY_SIMPLE_K_TEMP_MIN_PULSE_WIDTH_LOW_KEY, LIBRARY_SIMPLE_K_TEMP_NOCHANGE_FALL_KEY,
							LIBRARY_SIMPLE_K_TEMP_NOCHANGE_RISE_KEY, LIBRARY_SIMPLE_K_TEMP_PIN_CAP_KEY, LIBRARY_SIMPLE_K_TEMP_RECOVERY_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_RECOVERY_RISE_KEY,
							LIBRARY_SIMPLE_K_TEMP_REMOVAL_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_REMOVAL_RISE_KEY, LIBRARY_SIMPLE_K_TEMP_RISE_DELAY_INTERCEPT_KEY, LIBRARY_SIMPLE_K_TEMP_RISE_PIN_RESISTANCE_KEY,
							LIBRARY_SIMPLE_K_TEMP_RISE_PROPOGATION_KEY, LIBRARY_SIMPLE_K_TEMP_RISE_TRANSITION_KEY, LIBRARY_SIMPLE_K_TEMP_RISE_WIRE_RESISTANCE_KEY,
							LIBRARY_SIMPLE_K_TEMP_SETUP_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_SETUP_RISE_KEY, LIBRARY_SIMPLE_K_TEMP_SKEW_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_SKEW_RISE_KEY,
							LIBRARY_SIMPLE_K_TEMP_SLOPE_FALL_KEY, LIBRARY_SIMPLE_K_TEMP_SLOPE_RISE_KEY, LIBRARY_SIMPLE_K_TEMP_WIRE_CAP_KEY, LIBRARY_SIMPLE_K_TEMP_WIRE_RES_KEY,
							LIBRARY_SIMPLE_K_VOLT_CELL_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_CELL_LEAKAGE_POWER_KEY, LIBRARY_SIMPLE_K_VOLT_CELL_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_DRIVE_CURRENT_KEY,
							LIBRARY_SIMPLE_K_VOLT_DRIVE_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_DRIVE_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_FALL_PIN_RESISTANCE_KEY, LIBRARY_SIMPLE_K_VOLT_FALL_PROPAGATION_KEY,
							LIBRARY_SIMPLE_K_VOLT_FALL_TRANSITION_KEY, LIBRARY_SIMPLE_K_VOLT_HOLD_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_HOLD_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_INTERNAL_POWER_KEY,
							LIBRARY_SIMPLE_K_VOLT_INTRINSIC_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_INTRINSIC_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_MIN_PERIOD_KEY, LIBRARY_SIMPLE_K_VOLT_MIN_PULSE_WIDTH_HIGH_KEY,
							LIBRARY_SIMPLE_K_VOLT_MIN_PULSE_WIDTH_LOW_KEY, LIBRARY_SIMPLE_K_VOLT_NOCHANGE_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_NOCHANGE_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_PIN_CAP_KEY,
							LIBRARY_SIMPLE_K_VOLT_RECOVERY_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_RECOVERY_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_REMOVAL_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_REMOVAL_RISE_KEY,
							LIBRARY_SIMPLE_K_VOLT_RISE_DELAY_INTERCEPT_KEY, LIBRARY_SIMPLE_K_VOLT_RISE_PIN_RESISTANCE_KEY, LIBRARY_SIMPLE_K_VOLT_RISE_PROPAGATION_KEY,
							LIBRARY_SIMPLE_K_VOLT_RISE_TRANSITION_KEY, LIBRARY_SIMPLE_K_VOLT_SETUP_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_SETUP_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_SKEW_FALL_KEY,
							LIBRARY_SIMPLE_K_VOLT_SKEW_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_SLOPE_FALL_KEY, LIBRARY_SIMPLE_K_VOLT_SLOPE_RISE_KEY, LIBRARY_SIMPLE_K_VOLT_WIRE_CAP_KEY,
							LIBRARY_SIMPLE_K_VOLT_WIRE_RES_KEY]



	LIBRARY_COMPLEX_ATTR_KEY = [LIBRARY_COMPLEX_CAPACITIVE_LOAD_UNIT_KEY, LIBRARY_COMPLEX_DEFAULT_PART_KEY, LIBRARY_COMPLEX_DEFINE_KEY, LIBRARY_COMPLEX_DEFINE_CELL_AREA_KEY,
							LIBRARY_COMPLEX_DEFINE_GROUP_KEY, LIBRARY_COMPLEX_LIBRARY_FEATURES_KEY, LIBRARY_COMPLEX_PIECE_DEFINE_KEY, LIBRARY_COMPLEX_ROUTING_LAYERS_KEY, LIBRARY_COMPLEX_TECHNOLOGY_KEY,
							LIBRARY_COMPLEX_VOLTAGE_MAP_KEY]

	LIBRARY_GROUP_ATTR_KEY = [LIBRARY_GROUP_BASE_CURVES_KEY, LIBRARY_GROUP_BASE_CURVE_TYPE_KEY, LIBRARY_GROUP_CURVE_X_KEY, LIBRARY_GROUP_CURVE_Y_KEY, LIBRARY_GROUP_COMPACT_LUT_TEMPLATE_KEY,
						LIBRARY_GROUP_BASE_CURVES_GROUP_KEY, LIBRARY_GROUP_VARIABLE_1_KEY, LIBRARY_GROUP_VARIABLE_2_KEY, LIBRARY_GROUP_VARIABLE_3_KEY, LIBRARY_GROUP_VARIABLE_4_KEY,
						LIBRARY_GROUP_INDEX_1_KEY, LIBRARY_GROUP_INDEX_2_KEY, LIBRARY_GROUP_INDEX_3_KEY, LIBRARY_GROUP_DC_CURRENT_TEMPLATE_KEY, LIBRARY_GROUP_EM_LUT_TEMPLATE_KEY,
						LIBRARY_GROUP_FALL_NET_DELAY_KEY, LIBRARY_GROUP_FALL_TRANSITION_DEGRADATION_KEY, LIBRARY_GROUP_FAULTS_LUT_TEMPLATE_KEY, LIBRARY_GROUP_INPUT_VOLTAGE_KEY,
						LIBRARY_GROUP_FPGA_ISD_KEY, LIBRARY_GROUP_IV_LUT_TEMPLATE_KEY, LIBRARY_GROUP_LU_TABLE_TEMPLATE_KEY, LIBRARY_GROUP_MAXCAP_LUT_TEMPLATE_KEY,
						LIBRARY_GROUP_MAXTRANS_LUT_TEMPLATE_KEY, LIBRARY_GROUP_NOISE_LUT_TEMPLATE_KEY, LIBRARY_GROUP_NORMALIZED_DRIVER_WAVEFORM_KEY, LIBRARY_GROUP_OPERATING_CONDITIONS_KEY,
						LIBRARY_GROUP_OUTPUT_CURRENT_TEMPLATE_KEY, LIBRARY_GROUP_OUTPUT_VOLTAGE_KEY, LIBRARY_GROUP_PART_KEY, LIBRARY_GROUP_PG_CURRENT_TEMPLATE_KEY, LIBRARY_GROUP_POLY_TEMPLATE_KEY,
						LIBRARY_GROUP_POWER_LUT_TEMPLATE_KEY, LIBRARY_GROUP_POWER_POLY_TEMPLATE_KEY, LIBRARY_GROUP_POWER_SUPPLY_KEY, LIBRARY_GROUP_PROPAGATION_LUT_TEMPLATE_KEY,
						LIBRARY_GROUP_RISE_NET_DELAY_KEY, LIBRARY_GROUP_RISE_TRANSITION_DEGRADATION_KEY, LIBRARY_GROUP_SCALED_CELL_KEY, LIBRARY_GROUP_SENSITIZATION_KEY, LIBRARY_GROUP_PIN_NAMES_KEY,
						LIBRARY_GROUP_VECTOR_KEY, LIBRARY_GROUP_SCALING_FACTORS_KEY, LIBRARY_GROUP_TIMING_KEY, LIBRARY_GROUP_TIMING_RANGE_KEY, LIBRARY_GROUP_TYPE_KEY, LIBRARY_GROUP_USER_PARAMETERS_KEY,
						LIBRARY_GROUP_WIRE_LOAD_KEY, LIBRARY_GROUP_WIRE_LOAD_SELECTION_KEY, LIBRARY_GROUP_WIRE_LOAD_TABLE_KEY]


	CELL_SIMPLE_AREA_KEY = "area"
	CELL_SIMPLE_AUXILIARY_PAD_CELL_KEY = "auxiliary_pad_cell"
	CELL_SIMPLE_BASE_NAME_KEY = "base_name"
	CELL_SIMPLE_BUS_NAMING_STYLE_KEY = "bus_naming_style"
	CELL_SIMPLE_CELL_FOOTPRINT_KEY = "cell_footprint"
	CELL_SIMPLE_CELL_LEAKAGE_POWER_KEY = "cell_leakage_power"
	CELL_SIMPLE_CLOCK_GATING_INTEGRATED_CELL_KEY = "clock_gating_integrated_cell"
	CELL_SIMPLE_DONT_FAULT_KEY = "dont_fault"
	CELL_SIMPLE_DONT_TOUCH_KEY = "dont_touch"
	CELL_SIMPLE_DONT_USE_KEY = "dont_use"
	CELL_SIMPLE_DRIVER_TYPE_KEY = "driver_type"
	CELL_SIMPLE_EDIF_NAME_KEY = "edif_name:"
	CELL_SIMPLE_EM_TEMP_DEGRADATION_FACTOR_KEY = "em_temp_degradation_factor"
	CELL_SIMPLE_FPGA_DOMAIN_STYLE_KEY = "fpga_domain_style"
	CELL_SIMPLE_HANDLE_NEGATIVE_CONSTRAINT_KEY = "handle_negative_constraint"
	CELL_SIMPLE_INTERFACE_TIMING_KEY = "interface_timing"
	CELL_SIMPLE_IO_TYPE_KEY = "io_type"
	CELL_SIMPLE_IS_CLOCK_GATING_CELL_KEY = "is_clock_gating_cell"
	CELL_SIMPLE_MAP_ONLY_KEY = "map_only"
	CELL_SIMPLE_PAD_CELL_KEY = "pad_cell"
	CELL_SIMPLE_PAD_TYPE_KEY = "pad_type"
	CELL_SIMPLE_POWER_CELL_TYPE_KEY = "power_cell_type"
	CELL_SIMPLE_PREFERRED_KEY = "preferred"
	CELL_SIMPLE_SCALING_FACTORS_KEY = "scaling_factors"
	CELL_SIMPLE_SINGLE_BIT_DEGENERATE_KEY = "single_bit_degenerate"
	CELL_SIMPLE_SLEW_TYPE_KEY = "slew_type"
	CELL_SIMPLE_TIMING_MODEL_TYPE_KEY = "timing_model_type"
	CELL_SIMPLE_USE_FOR_SIZE_ONLY_KEY = "use_for_size_only"
	CELL_SIMPLE_VHDL_NAME_KEY = "vhdl_name"


	CELL_COMPLEX_PIN_EQUAL_KEY = "pin_equal"
	CELL_COMPLEX_PIN_OPPOSITE_KEY = "pin_opposite"
	CELL_COMPLEX_RAIL_CONNECTION_KEY = "rail_connection"
	CELL_COMPLEX_RESOURCE_USAGE_KEY = "resource_usage"


	CELL_GROUP_BUNDLE_KEY = "bundle"
	CELL_GROUP_BUS_KEY = "bus"
	CELL_GROUP_DYNAMIC_CURRENT_KEY = "dynamic_current"
	CELL_GROUP_FF_KEY = "ff"
	CELL_GROUP_FF_BANK_KEY = "ff_bank"
	CELL_GROUP_FUNCTIONAL_YIELD_METRIC_KEY = "functional_yield_metric"
	CELL_GROUP_GENERATED_CLOCK_KEY = "generated_clock"
	CELL_GROUP_INTRINSIC_PARASITIC_KEY = "intrinsic_parasitic"
	CELL_GROUP_LATCH_KEY = "latch"
	CELL_GROUP_LATCH_BANK_KEY = "latch_bank"
	CELL_GROUP_LEAKAGE_CURRENT_KEY = "leakage_current"
	CELL_GROUP_LEAKAGE_POWER_KEY = "leakage_power"
	CELL_GROUP_LUT_KEY = "lut"
	CELL_GROUP_MODE_DEFINITION_KEY = "mode_definition"
	CELL_GROUP_PIN_KEY = "pin"
	CELL_GROUP_ROUTING_TRACK_KEY = "routing_track"
	CELL_GROUP_STATETABLE_KEY = "statetable"
	CELL_GROUP_TEST_CELL_KEY = "test_cell"

	CELL_SIMPLE_ATTR_KEY = [CELL_SIMPLE_AREA_KEY, CELL_SIMPLE_AUXILIARY_PAD_CELL_KEY, CELL_SIMPLE_BASE_NAME_KEY, CELL_SIMPLE_BUS_NAMING_STYLE_KEY, CELL_SIMPLE_CELL_FOOTPRINT_KEY,
						CELL_SIMPLE_CELL_LEAKAGE_POWER_KEY, CELL_SIMPLE_CLOCK_GATING_INTEGRATED_CELL_KEY, CELL_SIMPLE_DONT_FAULT_KEY, CELL_SIMPLE_DONT_TOUCH_KEY,
						CELL_SIMPLE_DONT_USE_KEY, CELL_SIMPLE_DRIVER_TYPE_KEY, CELL_SIMPLE_EDIF_NAME_KEY, CELL_SIMPLE_EM_TEMP_DEGRADATION_FACTOR_KEY, CELL_SIMPLE_FPGA_DOMAIN_STYLE_KEY,
						CELL_SIMPLE_HANDLE_NEGATIVE_CONSTRAINT_KEY, CELL_SIMPLE_INTERFACE_TIMING_KEY, CELL_SIMPLE_IO_TYPE_KEY, CELL_SIMPLE_IS_CLOCK_GATING_CELL_KEY,
						CELL_SIMPLE_MAP_ONLY_KEY, CELL_SIMPLE_PAD_CELL_KEY, CELL_SIMPLE_PAD_TYPE_KEY, CELL_SIMPLE_POWER_CELL_TYPE_KEY, CELL_SIMPLE_PREFERRED_KEY,
						CELL_SIMPLE_SCALING_FACTORS_KEY, CELL_SIMPLE_SINGLE_BIT_DEGENERATE_KEY, CELL_SIMPLE_SLEW_TYPE_KEY, CELL_SIMPLE_TIMING_MODEL_TYPE_KEY,
						CELL_SIMPLE_USE_FOR_SIZE_ONLY_KEY, CELL_SIMPLE_VHDL_NAME_KEY]


	CELL_COMPLEX_ATTR_KEY = [CELL_COMPLEX_PIN_EQUAL_KEY, CELL_COMPLEX_PIN_OPPOSITE_KEY, CELL_COMPLEX_RAIL_CONNECTION_KEY, CELL_COMPLEX_RESOURCE_USAGE_KEY]

	CELL_GROUP_ATTR_KEY = [CELL_GROUP_BUNDLE_KEY, CELL_GROUP_BUS_KEY, CELL_GROUP_DYNAMIC_CURRENT_KEY, CELL_GROUP_FF_KEY, CELL_GROUP_FF_BANK_KEY, CELL_GROUP_FUNCTIONAL_YIELD_METRIC_KEY,
					CELL_GROUP_GENERATED_CLOCK_KEY, CELL_GROUP_INTRINSIC_PARASITIC_KEY, CELL_GROUP_LATCH_KEY, CELL_GROUP_LATCH_BANK_KEY, CELL_GROUP_LEAKAGE_CURRENT_KEY, CELL_GROUP_LEAKAGE_POWER_KEY,
					CELL_GROUP_LUT_KEY, CELL_GROUP_MODE_DEFINITION_KEY, CELL_GROUP_PIN_KEY, CELL_GROUP_ROUTING_TRACK_KEY, CELL_GROUP_STATETABLE_KEY, CELL_GROUP_TEST_CELL_KEY]

	PIN_SIMPLE_BUS_TYPE_KEY = "bus_type"

	PIN_SIMPLE_BIT_WIDTH_KEY = "bit_width"
	PIN_SIMPLE_CAPACITANCE_KEY = "capacitance"
	PIN_SIMPLE_CLOCK_KEY = "clock"
	PIN_SIMPLE_CLOCK_GATE_CLOCK_PIN_KEY = "clock_gate_clock_pin"
	PIN_SIMPLE_CLOCK_GATE_ENABLE_PIN_KEY = "clock_gate_enable_pin"
	PIN_SIMPLE_CLOCK_GATE_TEST_PIN_KEY = "clock_gate_test_pin"
	PIN_SIMPLE_CLOCK_GATE_OBS_PIN_KEY = "clock_gate_obs_pin"
	PIN_SIMPLE_CLOCK_GATE_OUT_PIN_KEY = "clock_gate_out_pin"
	PIN_SIMPLE_COMPLEMENTARY_PIN_KEY = "complementary_pin"
	PIN_SIMPLE_CONNECTION_CLASS_KEY = "connection_class"
	PIN_SIMPLE_DIRECTION_KEY = "direction"
	PIN_SIMPLE_DONT_FAULT_KEY = "dont_fault"
	PIN_SIMPLE_DRIVE_CURRENT_KEY = "drive_current"
	PIN_SIMPLE_DRIVER_TYPE_KEY = "driver_type"
	PIN_SIMPLE_FALL_CAPACITANCE_KEY = "fall_capacitance"
	PIN_SIMPLE_FALL_CURRENT_SLOPE_AFTER_THRESHOLD_KEY = "fall_current_slope_after_threshold"
	PIN_SIMPLE_FALL_CURRENT_SLOPE_BEFORE_THRESHOLD_KEY = "fall_current_slope_before_threshold"
	PIN_SIMPLE_FALL_TIME_AFTER_THRESHOLD_KEY = "fall_time_after_threshold"
	PIN_SIMPLE_FALL_TIME_BEFORE_THRESHOLD_KEY = "fall_time_before_threshold"
	PIN_SIMPLE_FANOUT_LOAD_KEY = "fanout_load"
	PIN_SIMPLE_FAULT_MODEL_KEY = "fault_model"
	PIN_SIMPLE_FUNCTION_KEY = "function"
	PIN_SIMPLE_HAS_BUILTIN_PAD_KEY = "has_builtin_pad"
	PIN_SIMPLE_HYSTERESIS_KEY = "hysteresis"
	PIN_SIMPLE_INPUT_MAP_KEY = "input_map"
	PIN_SIMPLE_INPUT_SIGNAL_LEVEL_KEY = "input_signal_level"
	PIN_SIMPLE_INPUT_VOLTAGE_KEY = "input_voltage"
	PIN_SIMPLE_INTERNAL_NODE_KEY = "internal_node"
	PIN_SIMPLE_INVERTED_OUTPUT_KEY = "inverted_output"
	PIN_SIMPLE_IS_PAD_KEY = "is_pad"
	PIN_SIMPLE_MAX_CAPACITANCE_KEY = "max_capacitance"
	PIN_SIMPLE_MAX_FANOUT_KEY = "max_fanout"
	PIN_SIMPLE_MAX_INPUT_NOISE_WIDTH_KEY = "max_input_noise_width"
	PIN_SIMPLE_MAX_TRANSITION_KEY = "max_transition"
	PIN_SIMPLE_MIN_CAPACITANCE_KEY = "min_capacitance"
	PIN_SIMPLE_MIN_FANOUT_KEY = "min_fanout"
	PIN_SIMPLE_MIN_INPUT_NOISE_WIDTH_KEY = "min_input_noise_width"
	PIN_SIMPLE_MIN_PERIOD_KEY = "min_period"
	PIN_SIMPLE_MIN_PULSE_WIDTH_HIGH_KEY = "min_pulse_width_high"
	PIN_SIMPLE_MIN_PULSE_WIDTH_LOW_KEY = "min_pulse_width_low"
	PIN_SIMPLE_MIN_TRANSITION_KEY = "min_transition"
	PIN_SIMPLE_MULTICELL_PAD_PIN_KEY = "multicell_pad_pin"
	PIN_SIMPLE_NEXTSTATE_TYPE_KEY = "nextstate_type"
	PIN_SIMPLE_OUTPUT_SIGNAL_LEVEL_KEY = "output_signal_level"
	PIN_SIMPLE_OUTPUT_VOLTAGE_KEY = "output_voltage"
	PIN_SIMPLE_PIN_FUNC_TYPE_KEY = "pin_func_type"
	PIN_SIMPLE_ACTIVE_RISING_KEY = "active_rising"
	PIN_SIMPLE_PREFER_TIED_KEY = "prefer_tied"
	PIN_SIMPLE_PRIMARY_OUTPUT_KEY = "primary_output"
	PIN_SIMPLE_PULLING_CURRENT_KEY = "pulling_current"
	PIN_SIMPLE_PULLING_RESISTANCE_KEY = "pulling_resistance"
	PIN_SIMPLE_RISE_CAPACITANCE_KEY = "rise_capacitance"
	PIN_SIMPLE_RISE_CURRENT_SLOPE_AFTER_THRESHOLD_KEY = "rise_current_slope_after_threshold"
	PIN_SIMPLE_RISE_CURRENT_SLOPE_BEFORE_THRESHOLD_KEY = "rise_current_slope_before_threshold"
	PIN_SIMPLE_RISE_TIME_AFTER_THRESHOLD_KEY = "rise_time_after_threshold"
	PIN_SIMPLE_RISE_TIME_BEFORE_THRESHOLD_KEY = "rise_time_before_threshold"
	PIN_SIMPLE_SIGNAL_TYPE_KEY = "signal_type"
	PIN_SIMPLE_TEST_SCAN_OUT_INVERTED_KEY = "test_scan_out_inverted"
	PIN_SIMPLE_TEST_SCAN_ENABLE_INVERTED_KEY = "test_scan_enable_inverted"
	PIN_SIMPLE_TEST_SCAN_CLOCK_A_KEY = "test_scan_clock_a"
	PIN_SIMPLE_SLEW_CONTROL_KEY = "slew_control"
	PIN_SIMPLE_STATE_FUNCTION_KEY = "state_function"
	PIN_SIMPLE_TEST_OUTPUT_ONLY_KEY = "test_output_only"
	PIN_SIMPLE_THREE_STATE_KEY = "three_state"
	PIN_SIMPLE_VHDL_NAME_KEY = "vhdl_name"
	PIN_SIMPLE_X_FUNCTION_KEY = "x_function"

	PIN_COMPLEX_RISE_CAPACITANCE_RANGE = "rise_capacitance_range"

	PIN_GROUP_ELECTROMIGRATION_KEY = "electromigration"
	PIN_GROUP_HYPERBOLIC_NOISE_ABOVE_HIGH_KEY = "hyperbolic_noise_above_high"
	PIN_GROUP_HYPERBOLIC_NOISE_BELOW_LOW_KEY = "hyperbolic_noise_below_low"
	PIN_GROUP_HYPERBOLIC_NOISE_HIGH_KEY = "hyperbolic_noise_high"
	PIN_GROUP_HYPERBOLIC_NOISE_LOW_KEY = "hyperbolic_noise_low"
	PIN_GROUP_INTERNAL_POWER_KEY = "internal_power"
	PIN_GROUP_MAX_TRANS_KEY = "max_trans"
	PIN_GROUP_MIN_PULSE_WIDTH_KEY = "min_pulse_width"
	PIN_GROUP_MINIMUM_PERIOD_KEY = "minimum_period"
	PIN_GROUP_TIMING_KEY = "timing"
	PIN_GROUP_TLATCH_KEY = "tlatch"


	PIN_SIMPLE_ATTR_KEY = [PIN_SIMPLE_BUS_TYPE_KEY, PIN_SIMPLE_BIT_WIDTH_KEY, PIN_SIMPLE_CAPACITANCE_KEY, PIN_SIMPLE_CLOCK_KEY, PIN_SIMPLE_CLOCK_GATE_CLOCK_PIN_KEY, PIN_SIMPLE_CLOCK_GATE_ENABLE_PIN_KEY,
						PIN_SIMPLE_CLOCK_GATE_TEST_PIN_KEY, PIN_SIMPLE_CLOCK_GATE_OBS_PIN_KEY, PIN_SIMPLE_CLOCK_GATE_OUT_PIN_KEY, PIN_SIMPLE_COMPLEMENTARY_PIN_KEY,
						PIN_SIMPLE_CONNECTION_CLASS_KEY, PIN_SIMPLE_DIRECTION_KEY, PIN_SIMPLE_DONT_FAULT_KEY, PIN_SIMPLE_DRIVE_CURRENT_KEY, PIN_SIMPLE_DRIVER_TYPE_KEY,
						PIN_SIMPLE_FALL_CAPACITANCE_KEY, PIN_SIMPLE_FALL_CURRENT_SLOPE_AFTER_THRESHOLD_KEY, PIN_SIMPLE_FALL_CURRENT_SLOPE_BEFORE_THRESHOLD_KEY, PIN_SIMPLE_FALL_TIME_AFTER_THRESHOLD_KEY,
						PIN_SIMPLE_FALL_TIME_BEFORE_THRESHOLD_KEY, PIN_SIMPLE_FANOUT_LOAD_KEY, PIN_SIMPLE_FAULT_MODEL_KEY, PIN_SIMPLE_FUNCTION_KEY, PIN_SIMPLE_HAS_BUILTIN_PAD_KEY, PIN_SIMPLE_HYSTERESIS_KEY,
						PIN_SIMPLE_INPUT_MAP_KEY, PIN_SIMPLE_INPUT_SIGNAL_LEVEL_KEY, PIN_SIMPLE_INPUT_VOLTAGE_KEY, PIN_SIMPLE_INTERNAL_NODE_KEY, PIN_SIMPLE_INVERTED_OUTPUT_KEY, PIN_SIMPLE_IS_PAD_KEY,
						PIN_SIMPLE_MAX_CAPACITANCE_KEY, PIN_SIMPLE_MAX_FANOUT_KEY, PIN_SIMPLE_MAX_INPUT_NOISE_WIDTH_KEY, PIN_SIMPLE_MAX_TRANSITION_KEY, PIN_SIMPLE_MIN_CAPACITANCE_KEY,
						PIN_SIMPLE_MIN_FANOUT_KEY, PIN_SIMPLE_MIN_INPUT_NOISE_WIDTH_KEY, PIN_SIMPLE_MIN_PERIOD_KEY, PIN_SIMPLE_MIN_PULSE_WIDTH_HIGH_KEY, PIN_SIMPLE_MIN_PULSE_WIDTH_LOW_KEY,
						PIN_SIMPLE_MIN_TRANSITION_KEY, PIN_SIMPLE_MULTICELL_PAD_PIN_KEY, PIN_SIMPLE_NEXTSTATE_TYPE_KEY, PIN_SIMPLE_OUTPUT_SIGNAL_LEVEL_KEY, PIN_SIMPLE_OUTPUT_VOLTAGE_KEY,
						PIN_SIMPLE_PIN_FUNC_TYPE_KEY, PIN_SIMPLE_ACTIVE_RISING_KEY, PIN_SIMPLE_PREFER_TIED_KEY, PIN_SIMPLE_PRIMARY_OUTPUT_KEY, PIN_SIMPLE_PULLING_CURRENT_KEY,
						PIN_SIMPLE_PULLING_RESISTANCE_KEY, PIN_SIMPLE_RISE_CAPACITANCE_KEY, PIN_SIMPLE_RISE_CURRENT_SLOPE_AFTER_THRESHOLD_KEY, PIN_SIMPLE_RISE_CURRENT_SLOPE_BEFORE_THRESHOLD_KEY,
						PIN_SIMPLE_RISE_TIME_AFTER_THRESHOLD_KEY, PIN_SIMPLE_RISE_TIME_BEFORE_THRESHOLD_KEY, PIN_SIMPLE_SIGNAL_TYPE_KEY, PIN_SIMPLE_TEST_SCAN_OUT_INVERTED_KEY,
						PIN_SIMPLE_TEST_SCAN_ENABLE_INVERTED_KEY, PIN_SIMPLE_TEST_SCAN_CLOCK_A_KEY, PIN_SIMPLE_SLEW_CONTROL_KEY, PIN_SIMPLE_STATE_FUNCTION_KEY, PIN_SIMPLE_TEST_OUTPUT_ONLY_KEY,
						PIN_SIMPLE_THREE_STATE_KEY, PIN_SIMPLE_VHDL_NAME_KEY, PIN_SIMPLE_X_FUNCTION_KEY]



	PIN_COMPLEX_ATTR_KEY = [PIN_COMPLEX_RISE_CAPACITANCE_RANGE]

	PIN_GROUP_ATTR_KEY = [PIN_GROUP_ELECTROMIGRATION_KEY, PIN_GROUP_HYPERBOLIC_NOISE_ABOVE_HIGH_KEY, PIN_GROUP_HYPERBOLIC_NOISE_BELOW_LOW_KEY, PIN_GROUP_HYPERBOLIC_NOISE_HIGH_KEY,
					PIN_GROUP_HYPERBOLIC_NOISE_LOW_KEY, PIN_GROUP_MAX_TRANS_KEY, PIN_GROUP_MIN_PULSE_WIDTH_KEY, PIN_GROUP_MINIMUM_PERIOD_KEY, PIN_GROUP_TLATCH_KEY,
					# PIN_GROUP_INTERNAL_POWER_KEY, PIN_GROUP_TIMING_KEY
					]

	PIN_PG_VOLTAGE_NAME_KEY = "voltage_name"
	PIN_PG_TYPE_KEY = "pg_type"


	PIN_PG_SIMPLE_ATTR_KEY = [PIN_PG_VOLTAGE_NAME_KEY, PIN_PG_TYPE_KEY]

	TIMING_SIMPLE_CLOCK_GATING_FLAG_KEY = "clock_gating_flag"
	TIMING_SIMPLE_DEFAULT_TIMING_KEY = "default_timing"
	TIMING_SIMPLE_FALL_RESISTANCE_KEY = "fall_resistance"
	TIMING_SIMPLE_FPGA_ARC_CONDITION_KEY = "fpga_arc_condition"
	TIMING_SIMPLE_FPGA_DOMAIN_STYLE_KEY = "fpga_domain_style"
	TIMING_SIMPLE_INTERDEPENDENCE_ID_KEY = "interdependence_id"
	TIMING_SIMPLE_INTRINSIC_FALL_KEY = "intrinsic_fall"
	TIMING_SIMPLE_INTRINSIC_RISE_KEY = "intrinsic_rise"
	TIMING_SIMPLE_RELATED_BUS_EQUIVALENT_KEY = "related_bus_equivalent"
	TIMING_SIMPLE_RELATED_BUS_PINS_KEY = "related_bus_pins"
	TIMING_SIMPLE_RELATED_OUTPUT_PIN_KEY = "related_output_pin"
	TIMING_SIMPLE_RELATED_PIN_KEY = "related_pin"
	TIMING_SIMPLE_RISE_RESISTANCE_KEY = "rise_resistance"
	TIMING_SIMPLE_SDF_COND_KEY = "sdf_cond"
	TIMING_SIMPLE_SDF_COND_END_KEY = "sdf_cond_end"
	TIMING_SIMPLE_SDF_COND_START_KEY = "sdf_cond_start"
	TIMING_SIMPLE_SDF_EDGES_KEY = "sdf_edges"
	TIMING_SIMPLE_SLOPE_FALL_KEY = "slope_fall"
	TIMING_SIMPLE_SLOPE_RISE_KEY = "slope_rise"
	TIMING_SIMPLE_STEADY_STATE_RESISTANCE_ABOVE_HIGH_KEY = "steady_state_resistance_above_high"
	TIMING_SIMPLE_STEADY_STATE_RESISTANCE_BELOW_LOW_KEY = "steady_state_resistance_below_low"
	TIMING_SIMPLE_STEADY_STATE_RESISTANCE_HIGH_KEY = "steady_state_resistance_high"
	TIMING_SIMPLE_STEADY_STATE_RESISTANCE_LOW_KEY = "steady_state_resistance_low"
	TIMING_SIMPLE_TIED_OFF_KEY = "tied_off"
	TIMING_SIMPLE_TIMING_SENSE_KEY = "timing_sense"
	TIMING_SIMPLE_TIMING_TYPE_KEY = "timing_type"
	TIMING_SIMPLE_WHEN_KEY = "when"
	TIMING_SIMPLE_WHEN_END_KEY = "when_end"
	TIMING_SIMPLE_WHEN_START_KEY = "when_start"

	TIMING_COMPLEX_FALL_DELAY_INTERCEPT_KEY = "fall_delay_intercept"
	TIMING_COMPLEX_FALL_PIN_RESISTANCE_KEY = "fall_pin_resistance"
	TIMING_COMPLEX_MODE_KEY = "mode"
	TIMING_COMPLEX_RISE_DELAY_INTERCEPT_KEY = "rise_delay_intercept"
	TIMING_COMPLEX_RISE_PIN_RESISTANCE_KEY = "rise_pin_resistance"

	TIMING_GROUP_CELL_DEGRADATION_KEY = "cell_degradation"
	TIMING_GROUP_CELL_FALL_KEY = "cell_fall"
	TIMING_GROUP_CELL_RISE_KEY = "cell_rise"
	TIMING_GROUP_FALL_CONSTRAINT_KEY = "fall_constraint"
	TIMING_GROUP_FALL_PROPAGATION_KEY = "fall_propagation"
	TIMING_GROUP_FALL_TRANSITION_KEY = "fall_transition"
	TIMING_GROUP_NOISE_IMMUNITY_ABOVE_HIGH_KEY = "noise_immunity_above_high"
	TIMING_GROUP_NOISE_IMMUNITY_BELOW_LOW_KEY = "noise_immunity_below_low"
	TIMING_GROUP_NOISE_IMMUNITY_HIGH_KEY = "noise_immunity_high"
	TIMING_GROUP_NOISE_IMMUNITY_LOW_KEY = "noise_immunity_low"
	TIMING_GROUP_OUTPUT_CURRENT_FALL_KEY = "output_current_fall"
	TIMING_GROUP_OUTPUT_CURRENT_RISE_KEY = "output_current_rise"
	TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_ABOVE_HIGH_KEY = "propogated_noise_height_above_high"
	TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_BELOW_LOW_KEY = "propogated_noise_height_below_low"
	TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_HIGH_KEY = "propogated_noise_height_high"
	TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_LOW_KEY = "propogated_noise_height_low"
	TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO_ABOVE_HIGH_KEY = "propogated_noise_peak_time_ratio_above_high"
	TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO__BELOW_LOW_KEY = "propogated_noise_peak_time_ratio__below_low"
	TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO_HIGH_KEY = "propogated_noise_peak_time_ratio_high"
	TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO_LOW_KEY = "propogated_noise_peak_time_ratio_low"
	TIMING_GROUP_PROPOGATED_NOISE_WIDTH_ABOVE_HIGH_KEY = "propogated_noise_width_above_high"
	TIMING_GROUP_PROPOGATED_NOISE_WIDTH_BELOW_LOW_KEY = "propogated_noise_width_below_low"
	TIMING_GROUP_PROPOGATED_NOISE_WIDTH_HIGH_KEY = "propogated_noise_width_high"
	TIMING_GROUP_PROPOGATED_NOISE_WIDTH_LOW_KEY = "propogated_noise_width_low"
	TIMING_GROUP_RECEIVER_CAPACITANCE1_FALL_KEY = "receiver_capacitance1_fall"
	TIMING_GROUP_RECEIVER_CAPACITANCE1_RISE_KEY = "receiver_capacitance1_rise"
	TIMING_GROUP_RECEIVER_CAPACITANCE2_FALL_KEY = "receiver_capacitance2_fall"
	TIMING_GROUP_RECEIVER_CAPACITANCE2_RISE_KEY = "receiver_capacitance2_rise"
	TIMING_GROUP_RETAINING_FALL_KEY = "retaining_fall"
	TIMING_GROUP_RETAINING_RISE_KEY = "retaining_rise"
	TIMING_GROUP_RETAIN_FALL_SLEW_KEY = "retain_fall_slew"
	TIMING_GROUP_RETAIN_RISE_SLEW_KEY = "retain_rise_slew"
	TIMING_GROUP_RISE_CONSTRAINT_KEY = "rise_constraint"
	TIMING_GROUP_RISE_PROPAGATION_KEY = "rise_propagation"
	TIMING_GROUP_RISE_TRANSITION_KEY = "rise_transition"
	TIMING_GROUP_STEADY_STATE_CURRENT_HIGH_KEY = "steady_state_current_high"
	TIMING_GROUP_STEADY_STATE_CURRENT_LOW_KEY = "steady_state_current_low"
	TIMING_GROUP_STEADY_STATE_CURRENT_TRISTATE_KEY = "steady_state_current_tristate"


	TIMING_SIMPLE_ATTR_KEY = [TIMING_SIMPLE_CLOCK_GATING_FLAG_KEY, TIMING_SIMPLE_DEFAULT_TIMING_KEY, TIMING_SIMPLE_FALL_RESISTANCE_KEY, TIMING_SIMPLE_FPGA_ARC_CONDITION_KEY,
							TIMING_SIMPLE_FPGA_DOMAIN_STYLE_KEY, TIMING_SIMPLE_INTERDEPENDENCE_ID_KEY, TIMING_SIMPLE_INTRINSIC_FALL_KEY, TIMING_SIMPLE_INTRINSIC_RISE_KEY,
							TIMING_SIMPLE_RELATED_BUS_EQUIVALENT_KEY, TIMING_SIMPLE_RELATED_BUS_PINS_KEY, TIMING_SIMPLE_RELATED_OUTPUT_PIN_KEY, TIMING_SIMPLE_RELATED_PIN_KEY,
							TIMING_SIMPLE_RISE_RESISTANCE_KEY, TIMING_SIMPLE_SDF_COND_KEY, TIMING_SIMPLE_SDF_COND_END_KEY, TIMING_SIMPLE_SDF_COND_START_KEY, TIMING_SIMPLE_SDF_EDGES_KEY,
							TIMING_SIMPLE_SLOPE_FALL_KEY, TIMING_SIMPLE_SLOPE_RISE_KEY, TIMING_SIMPLE_STEADY_STATE_RESISTANCE_ABOVE_HIGH_KEY, TIMING_SIMPLE_STEADY_STATE_RESISTANCE_BELOW_LOW_KEY,
							TIMING_SIMPLE_STEADY_STATE_RESISTANCE_HIGH_KEY, TIMING_SIMPLE_STEADY_STATE_RESISTANCE_LOW_KEY, TIMING_SIMPLE_TIED_OFF_KEY, TIMING_SIMPLE_TIMING_SENSE_KEY, TIMING_SIMPLE_TIMING_TYPE_KEY,
							TIMING_SIMPLE_WHEN_KEY, TIMING_SIMPLE_WHEN_END_KEY, TIMING_SIMPLE_WHEN_START_KEY, ]

	TIMING_COMPLEX_ATTR_KEY = [TIMING_COMPLEX_FALL_DELAY_INTERCEPT_KEY, TIMING_COMPLEX_FALL_PIN_RESISTANCE_KEY, TIMING_COMPLEX_MODE_KEY, TIMING_COMPLEX_RISE_DELAY_INTERCEPT_KEY, TIMING_COMPLEX_RISE_PIN_RESISTANCE_KEY]

	TIMING_GROUP_ATTR_KEY = [TIMING_GROUP_CELL_DEGRADATION_KEY, TIMING_GROUP_CELL_FALL_KEY, TIMING_GROUP_CELL_RISE_KEY, TIMING_GROUP_FALL_CONSTRAINT_KEY, TIMING_GROUP_FALL_PROPAGATION_KEY,
					TIMING_GROUP_FALL_TRANSITION_KEY, TIMING_GROUP_NOISE_IMMUNITY_ABOVE_HIGH_KEY, TIMING_GROUP_NOISE_IMMUNITY_BELOW_LOW_KEY, TIMING_GROUP_NOISE_IMMUNITY_HIGH_KEY,
					TIMING_GROUP_NOISE_IMMUNITY_LOW_KEY, TIMING_GROUP_OUTPUT_CURRENT_FALL_KEY, TIMING_GROUP_OUTPUT_CURRENT_RISE_KEY, TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_ABOVE_HIGH_KEY,
					TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_BELOW_LOW_KEY, TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_HIGH_KEY, TIMING_GROUP_PROPOGATED_NOISE_HEIGHT_LOW_KEY,
					TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO_ABOVE_HIGH_KEY, TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO__BELOW_LOW_KEY,
					TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO_HIGH_KEY, TIMING_GROUP_PROPOGATED_NOISE_PEAK_TIME_RATIO_LOW_KEY, TIMING_GROUP_PROPOGATED_NOISE_WIDTH_ABOVE_HIGH_KEY,
					TIMING_GROUP_PROPOGATED_NOISE_WIDTH_BELOW_LOW_KEY, TIMING_GROUP_PROPOGATED_NOISE_WIDTH_HIGH_KEY, TIMING_GROUP_PROPOGATED_NOISE_WIDTH_LOW_KEY,
					TIMING_GROUP_RECEIVER_CAPACITANCE1_FALL_KEY, TIMING_GROUP_RECEIVER_CAPACITANCE1_RISE_KEY, TIMING_GROUP_RECEIVER_CAPACITANCE2_FALL_KEY, TIMING_GROUP_RECEIVER_CAPACITANCE2_RISE_KEY,
					TIMING_GROUP_RETAINING_FALL_KEY, TIMING_GROUP_RETAINING_RISE_KEY, TIMING_GROUP_RETAIN_FALL_SLEW_KEY, TIMING_GROUP_RETAIN_RISE_SLEW_KEY, TIMING_GROUP_RISE_CONSTRAINT_KEY,
					TIMING_GROUP_RISE_PROPAGATION_KEY, TIMING_GROUP_RISE_TRANSITION_KEY, TIMING_GROUP_STEADY_STATE_CURRENT_HIGH_KEY, TIMING_GROUP_STEADY_STATE_CURRENT_LOW_KEY,
					TIMING_GROUP_STEADY_STATE_CURRENT_TRISTATE_KEY]

	INTERNAL_POWER_SIMPLE_EQUAL_OR_OPPOSITE_OUTPUT_KEY = "equal_or_opposite_output"
	INTERNAL_POWER_SIMPLE_FALLING_TOGETHER_GROUP_KEY = "falling_together_group"
	INTERNAL_POWER_SIMPLE_POWER_LEVEL_KEY = "power_level"
	INTERNAL_POWER_SIMPLE_RELATED_PIN_KEY = "related_pin"
	INTERNAL_POWER_SIMPLE_RISING_TOGETHER_GROUP_KEY = "rising_together_group"
	INTERNAL_POWER_SIMPLE_SWITCHING_INTERVAL_KEY = "switching_interval"
	INTERNAL_POWER_SIMPLE_SWITCHING_TOGETHER_GROUP_KEY = "switching_together_group"
	INTERNAL_POWER_SIMPLE_WHEN_KEY = "when"

	INTERNAL_POWER_GROUP_RISE_POWER_KEY = "rise_power"
	INTERNAL_POWER_GROUP_POWER_KEY = "power"
	INTERNAL_POWER_GROUP_FALL_POWER_KEY = "fall_power"
	INTERNAL_POWER_GROUP_DOMAIN_KEY = "domain"


	INTERNAL_POWER_SIMPLE_ATTR_KEY = [INTERNAL_POWER_SIMPLE_EQUAL_OR_OPPOSITE_OUTPUT_KEY, INTERNAL_POWER_SIMPLE_FALLING_TOGETHER_GROUP_KEY, INTERNAL_POWER_SIMPLE_POWER_LEVEL_KEY,
									INTERNAL_POWER_SIMPLE_RELATED_PIN_KEY, INTERNAL_POWER_SIMPLE_RISING_TOGETHER_GROUP_KEY, INTERNAL_POWER_SIMPLE_SWITCHING_INTERVAL_KEY,
									INTERNAL_POWER_SIMPLE_SWITCHING_TOGETHER_GROUP_KEY, INTERNAL_POWER_SIMPLE_WHEN_KEY]

	INTERNAL_POWER_GROUP_ATTR_KEY = [INTERNAL_POWER_GROUP_RISE_POWER_KEY, INTERNAL_POWER_GROUP_POWER_KEY, INTERNAL_POWER_GROUP_FALL_POWER_KEY, INTERNAL_POWER_GROUP_DOMAIN_KEY]


	LIB_ATTR_TOTAL_OUTPUT_NET_CAPACITANCE_KEY = "total_output_net_capacitance"
	LIB_ATTR_INPUT_NET_TRANSITION_KEY = "input_net_transition"
	LIB_ATTR_CONSTRAINED_PIN_TRANSITION_KEY = "constrained_pin_transition"

	TIMING_SIMPLE_ATTR_HOLD_FALLING = "hold_falling"
	TIMING_SIMPLE_ATTR_SETUP_FALLING = "setup_falling"
	TIMING_SIMPLE_ATTR_HOLD_RISING = "hold_rising"
	TIMING_SIMPLE_ATTR_SETUP_RISING = "setup_rising"

	LIB_BRACKET_LEVEL = 0
	CELL_BRACKET_LEVEL = 1
	PIN_BRACKET_LEVEL = 2
	PIN_BUS_BRACKET_LEVEL = 2
	PIN_BUS_RANGE_BRACKET_LEVEL = 3
	TIMING_BRACKET_LEVEL = 3
	TIMING_RANGE_BRACKET_LEVEL = 4
	INTERNAL_POWER_BRACKET_LEVEL = 3
	INTERNAL_POWER_RANGE_BRACKET_LEVEL = 4

class NETLIST_KEYS():
	NETLIST_SUB_CKT_KEY = ".SUBCKT"
	NETLIST_APPEND_LINE_KEY = "+ "
	NETLIST_COMMENT_KEY = "*"
	NETLIST_PIN_INFO_KEY = "*.PININFO"

	NETLIST_X_INST_KEY = "X"
	NETLIST_M_INST_KEY = "M"
	NETLIST_R_INST_KEY = "R"
	NETLIST_D_INST_KEY = "D"

	NETLIST_END_CKT_KEY = ".ENDS"
	NETLIST_NMOS = "nch"
	NETLIST_PMOS = "pch"

class GDS_KEYS():
	GDS_CELL_KEY = "cell"
	GDS_BOUNDARY_KEY = "b"
	GDS_PATH_KEY = "p"
	GDS_TEXT_KEY = "t"
	GDS_SREF_KEY = "s"
	GDS_AREF_KEY = "a"
	GDS_NODE_KEY = "n"
	GDS_BOX_KEY = "x"
	GDS_WIDTH_KEY = "w"

	GDS_COMMENT_KEY = "#"

	GDS_START_BRACKET_KEY = "{"
	GDS_END_BRACKET_KEY = "}"
	GDS_CELL_BRACKET_LEVEL = 2
	GDS_CELL_END_BRACKET_LEVEL = 1
	GDS_FILE_END_BRACKET_LEVEL = 0
	
	GDS_RECT_TYPE = "RECT"
	GDS_PATH_TYPE = "PATH"


class CFG_KEYW():
	
	BOUNDARY_KEY = "layer_boundary"
	NETLIST_PATH = "netlist_path"
	NETLIST_FILES_NAME = "netlist_files_name"
	NETLIST_FILE_EXT = "netlist_file_extension"

	GDS_PATH = "gds_path"
	GDS_FILES_NAME = "gds_files_name"
	GDS_FILE_EXT = "gds_file_extension"

	VERILOG_PATH = "verilog_path"
	VERILOG_FILES_NAME = "verilog_files_name"
	VERILOG_FILE_EXT = "verilog_file_extension"

	LEF_PATH = "lef_path"
	LEF_FILES_NAME = "lef_files_name"
	LEF_FILE_EXT = "lef_file_extension"
	
	TETRAMAX_PATH = "tetramax_path"
	TETRAMAX_FILES_NAME = "tetramax_files_name"
	TETRAMAX_FILE_EXT = "tetramax_file_extension"

	TESSENT_PATH = "tessent_path"
	TESSENT_FILES_NAME = "tessent_files_name"
	TESSENT_FILE_EXT = "tessent_file_extension"	
	
	LIB_PATH = "lib_path"
	LIB_FILES_NAME = "lib_files_name"
	LIB_FILE_EXT = "lib_file_extension"

	LIST_QA = "list_qa"
	LIST_CONS = "list_cons"
	LIST_CONS_FILE = "consistency_lookup_file"

	OUT_DIR = "out_dir"
	IP_TAG_ROOT = "ip_tag_root"
	NUMBER_LINE_PAGE = "number_line_page"
	LAYER_MAPPING = "layer_mapping"

	CUSTOM_LAYER_MAPPING = "layer_mapping"
	LIST_GROUND_NAME = "list_ground_name"
	LIST_POWER_NAME = "list_power_name"
	LIST_PMOS_NAME = "list_pmos_name"
	LIST_NMOS_NAME = "list_nmos_name"
	
class TETRAMAX_KEYS():
	TETRAMAX_BRACKET_START_KEY = "("
	TETRAMAX_BRACKET_END_KEY = ")"
	TETRAMAX_END_STATEMENT_KEY = ";"
	TETRAMAX_START_MODULE_KEY = "module"
	TETRAMAX_END_MODULE_KEY = "endmodule"
	TETRAMAX_PIN_INPUT_KEY = "input"
	TETRAMAX_PIN_OUTPUT_KEY = "output"
	TETRAMAX_PIN_INOUT_KEY = "inout"
	TETRAMAX_PIN_START_BUS_KEY = "["
	TETRAMAX_PIN_END_BUS_KEY = "]"
	TETRAMAX_PARAMETER_KEY = "parameter"
	TETRAMAX_END_STATEMENT_KEY = ";"

class TESSENT_KEYS():
	TESSENT_BRACKET_START_KEY = "("
	TESSENT_BRACKET_END_KEY = ")"
	TESSENT_END_STATEMENT_KEY = ";"
	TESSENT_START_MODULE_KEY = "model"
	TESSENT_PIN_INPUT_KEY = "input"
	TESSENT_PIN_OUTPUT_KEY = "output"
	TESSENT_PIN_INOUT_KEY = "inout"

class nameCheck():#for CONS009
	layout_path = 'layout_path'
	nestlist_path = 'nestlist_path'
	rule_file = 'rule_file'
	tool = 'tool'
	execution_time = 'execution_time'
	verfy_path = 'verfy_path'
	tool_version = 'tool_version'
	nestlist_name = 'nestlist_name'
	layout_name = 'layout_name'
	incorrect = "INCORRECT"
	result = 'result'


class header():#for CONS009
	relaHeader = {
        # nameCheck.rule				: 'REPORT FILE NAME:',
        nameCheck.layout_path				: 'LAYOUT NAME:',
        nameCheck.nestlist_path				: 'SOURCE NAME:',
        nameCheck.rule_file					: 'RULE FILE:',
        nameCheck.tool						: 'CALIBRE',
        nameCheck.execution_time			: 'CREATION TIME:',
        nameCheck.verfy_path				: 'CURRENT DIRECTORY:',
        nameCheck.tool_version				: 'CALIBRE VERSION:',
        nameCheck.nestlist_name 			: 'SOURCE CELL NAME:',
        nameCheck.layout_name				: 'LAYOUT CELL NAME:'
    }
	toWrite = [
        {nameCheck.nestlist_name: 'Netlist cell name'},
        {nameCheck.layout_name: 'Layout cell name'},
        {nameCheck.layout_path: 'Layout path'},
        {nameCheck.nestlist_path: 'Netlist path'},
        {nameCheck.result: 'Result'},
        {nameCheck.rule_file: 'Rule file'},
        {'spec': 'Special modification to the rule file'},
        {nameCheck.tool: 'Tool'},
        {nameCheck.tool_version: 'Tool version'},
        {nameCheck.execution_time: 'Execution time'},
        {nameCheck.verfy_path: 'Verification directory'}
    ]


class QA_IDS():

	CONS001 = "CONS001"
	CONS002 = "CONS002"
	CONS003 = "CONS003"
	CONS004 = "CONS004"
	CONS005 = "CONS005"
	CONS006 = "CONS006"
	CONS007 = "CONS007"
	CONS008 = "CONS008"
	CONS009 = "CONS009"
	LEF001 = "LEF001"
	LEF002 = "LEF002"
	LEF003 = "LEF003"
	LEF004 = "LEF004"
	LEF005 = "LEF005"
	LEF006 = "LEF006"
	LEF007 = "LEF007"
	LEF008 = "LEF008"
	LEF009 = "LEF009"
	LEF010 = "LEF010"
	LEF011 = "LEF011"
	LEF012 = "LEF012"
	LEF013 = "LEF013"
	LEF014 = "LEF014"
	LEF015 = "LEF015"
	LEF016 = "LEF016"
	LEF017 = "LEF017"
	LEF018 = "LEF018"
	LEF019 = "LEF019"
	LEF020 = "LEF020"
	LEF021 = "LEF021"
	LEF022 = "LEF022"
	LEF023 = "LEF023"
	LEF024 = "LEF024"
	LEF025 = "LEF025"
	
	GDS001 = "GDS001"
	GDS002 = "GDS002"
	GDS003 = "GDS003"
	GDS004 = "GDS004"
	GDS005 = "GDS005"
	GDS006 = "GDS006"
	GDS007 = "GDS007"
	GDS008 = "GDS008"
	GDS009 = "GDS009"
	GDS010 = "GDS010"
	GDS011 = "GDS011"
	GDS012 = "GDS012"
	GDS013 = "GDS013"
	GDS014 = "GDS014"
# 	GDS015 = "GDS015"
	
	CDL001 = "CDL001"
	CDL002 = "CDL002"
	CDL003 = "CDL003"
	CDL004 = "CDL004"
	VER001 = "VER001"
	VER002 = "VER002"
	VER003 = "VER003"
	VER004 = "VER004"
	VER005 = "VER005"
	VER006 = "VER006"
	VER007 = "VER007"
	VER008 = "VER008"
	LIB001 = "LIB001"
	LIB002 = "LIB002"
	LIB003 = "LIB003"
	LIB004 = "LIB004"
	LIB005 = "LIB005"
	LIB006 = "LIB006"
	LIB007 = "LIB007"
	LIB008 = "LIB008"
	LIB009 = "LIB009"
	LIB010 = "LIB010"
	LIB011 = "LIB011"
	LIB012 = "LIB012"
	LIB013 = "LIB013"
	LIB014 = "LIB014"
	LIB015 = "LIB015"
	LIB016 = "LIB016"
	LIB017 = "LIB017"
	LIB018 = "LIB018"
	LIB019 = "LIB019"
	LIB020 = "LIB020"
	LIB021 = "LIB021"
	LIB022 = "LIB022"
	LIB023 = "LIB023"
	LIB024 = "LIB024"
	LIB025 = "LIB025"
	LIB026 = "LIB026"
	LIB027 = "LIB027"
	LIB028 = "LIB028"
	LIB029 = "LIB029"
	LIB030 = "LIB030"
	LIB031 = "LIB031"
	LIB032 = "LIB032"
	LIB033 = "LIB033"
	LIB034 = "LIB034"
	LIB035 = "LIB035"
	ABS001 = "ABS001"
	ABS002 = "ABS002"
	
	
	###############################################################################################################################################################################################################################################
	############################################################################################  LIST SUPPORT TEST CONFIG ########################################################################################################################
	LIST_ITEM_SUPPORT_FULL = ["CONS001", "CONS002", "CONS003", "CONS004", "CONS006", "CONS007", "CONS009", "LEF001", "LEF002", "LEF003", "LEF004", "LEF005", "LEF006", "LEF007", "LEF008", "LEF009", "LEF010", "LEF011", "LEF012", "LEF013",
	"LEF014", "LEF015", "LEF016", "LEF017", "LEF018", "LEF019", "LEF020", "LEF021", "LEF022", "LEF023", "LEF024", "LEF025", "GDS001", "GDS002", "GDS003", "GDS004", "GDS005", "GDS006", "GDS007", "GDS008", "GDS009", "GDS010", "GDS011", "GDS012", "GDS013",
	"GDS014", "CDL001", "CDL002", "CDL003", "CDL004", "VER001", "VER002", "VER003", "VER004", "VER005", "VER006", "VER007", "VER008", "LIB001", "LIB002", "LIB003", "LIB004", "LIB005", "LIB006", "LIB007", "LIB008", "LIB009", "LIB010", "LIB011", "LIB012",
	"LIB013", "LIB014", "LIB015", "LIB016", "LIB017", "LIB018", "LIB019", "LIB020", "LIB021", "LIB022", "LIB023", "LIB024", "LIB025", "LIB026", "LIB027", "LIB028", "LIB029", "LIB030", "LIB031", "LIB032", "LIB033", "LIB034", "LIB035", "ABS001", "ABS002"]
	############################################################################################################################################################################################################################################
	##################################################################################################################################################################################################################################################
	
	
